project_id = "nnyxtaftwispowolajpl"

[auth]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false

[functions.bazaar-stripe-webhook]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false
