import type { Job } from "./types";

// Illustrative dataset only — wire up to Supabase / Elasticsearch once the real job index ships.
export const MOCK_JOBS: Job[] = [
  {
    id: "job-001", title: "Senior Frontend Engineer (React)", companyId: "nova-systems", companyName: "Nova Systems", companyLogoColor: "#6366f1",
    location: "Remote", country: "United States", city: "Remote", salaryMin: 110000, salaryMax: 145000, currency: "USD",
    type: "full-time", workMode: "remote", experienceLevel: "senior", education: "Bachelor's degree", categoryId: "technology",
    skills: ["React", "TypeScript", "Accessibility", "GraphQL"], postedAt: "2026-06-28", isUrgent: true, isAccessible: true,
    isVisaSponsorship: false, isAiJob: false, description: "Own the frontend architecture for a fast-growing SaaS product, with a strong focus on accessible, inclusive UI.",
  },
  {
    id: "job-002", title: "Machine Learning Engineer", companyId: "vertex-ai-labs", companyName: "Vertex AI Labs", companyLogoColor: "#a855f7",
    location: "Berlin, Germany", country: "Germany", city: "Berlin", salaryMin: 75000, salaryMax: 98000, currency: "EUR",
    type: "full-time", workMode: "hybrid", experienceLevel: "mid", education: "Master's degree", categoryId: "ai",
    skills: ["Python", "PyTorch", "NLP"], postedAt: "2026-06-30", isUrgent: false, isAccessible: false,
    isVisaSponsorship: true, isAiJob: true, description: "Build and ship production ML models for our conversational AI platform.",
  },
  {
    id: "job-003", title: "Registered Nurse — ICU", companyId: "brightpath-health", companyName: "BrightPath Health", companyLogoColor: "#10b981",
    location: "Toronto, Canada", country: "Canada", city: "Toronto", salaryMin: 68000, salaryMax: 82000, currency: "CAD",
    type: "full-time", workMode: "onsite", experienceLevel: "mid", education: "Nursing degree", categoryId: "healthcare",
    skills: ["Critical Care", "Patient Support"], postedAt: "2026-06-25", isUrgent: true, isAccessible: true,
    isVisaSponsorship: true, isAiJob: false, description: "Join our ICU team providing critical care in a fully accessible, inclusive hospital environment.",
  },
  {
    id: "job-004", title: "Financial Analyst", companyId: "atlas-finance", companyName: "Atlas Finance Group", companyLogoColor: "#0ea5e9",
    location: "London, UK", country: "United Kingdom", city: "London", salaryMin: 45000, salaryMax: 60000, currency: "GBP",
    type: "full-time", workMode: "onsite", experienceLevel: "entry", education: "Bachelor's degree", categoryId: "finance",
    skills: ["Excel", "Financial Modeling"], postedAt: "2026-06-20", isUrgent: false, isAccessible: false,
    isVisaSponsorship: false, isAiJob: false, description: "Support portfolio reporting and forecasting for our investment management team.",
  },
  {
    id: "job-005", title: "Product Designer", companyId: "clearview-design", companyName: "Clearview Design Studio", companyLogoColor: "#ec4899",
    location: "Remote", country: "Remote", city: "Remote", salaryMin: 60000, salaryMax: 85000, currency: "USD",
    type: "freelance", workMode: "remote", experienceLevel: "mid", education: "Not required", categoryId: "design",
    skills: ["Figma", "Design Systems", "Accessibility"], postedAt: "2026-06-29", isUrgent: false, isAccessible: true,
    isVisaSponsorship: false, isAiJob: false, description: "Design accessible, delightful product experiences for our client portfolio.",
  },
  {
    id: "job-006", title: "Logistics Coordinator", companyId: "greenfield-logistics", companyName: "Greenfield Logistics", companyLogoColor: "#f59e0b",
    location: "Dubai, UAE", country: "United Arab Emirates", city: "Dubai", salaryMin: 30000, salaryMax: 42000, currency: "USD",
    type: "full-time", workMode: "onsite", experienceLevel: "entry", education: "Diploma", categoryId: "logistics",
    skills: ["Supply Chain", "Coordination"], postedAt: "2026-06-18", isUrgent: false, isAccessible: false,
    isVisaSponsorship: true, isAiJob: false, description: "Coordinate cross-border shipments and vendor relationships across the GCC region.",
  },
  {
    id: "job-007", title: "High School Mathematics Teacher", companyId: "summit-education", companyName: "Summit Education Group", companyLogoColor: "#14b8a6",
    location: "Sydney, Australia", country: "Australia", city: "Sydney", salaryMin: 58000, salaryMax: 72000, currency: "AUD",
    type: "full-time", workMode: "onsite", experienceLevel: "mid", education: "Teaching certification", categoryId: "education",
    skills: ["Curriculum Design", "Classroom Management"], postedAt: "2026-06-22", isUrgent: false, isAccessible: true,
    isVisaSponsorship: true, isAiJob: false, description: "Teach mathematics to grades 9-12 in an inclusive, learner-centered classroom.",
  },
  {
    id: "job-008", title: "Manufacturing Process Engineer", companyId: "orbit-manufacturing", companyName: "Orbit Manufacturing Co.", companyLogoColor: "#f97316",
    location: "Osaka, Japan", country: "Japan", city: "Osaka", salaryMin: 5200000, salaryMax: 6800000, currency: "JPY",
    type: "full-time", workMode: "onsite", experienceLevel: "senior", education: "Bachelor's degree", categoryId: "manufacturing",
    skills: ["Lean Manufacturing", "Six Sigma"], postedAt: "2026-06-15", isUrgent: false, isAccessible: false,
    isVisaSponsorship: true, isAiJob: false, description: "Optimize production lines and lead continuous-improvement initiatives.",
  },
  {
    id: "job-009", title: "Hotel Guest Experience Manager", companyId: "hearthstone-hospitality", companyName: "Hearthstone Hospitality", companyLogoColor: "#8b5cf6",
    location: "Barcelona, Spain", country: "Spain", city: "Barcelona", salaryMin: 32000, salaryMax: 41000, currency: "EUR",
    type: "full-time", workMode: "onsite", experienceLevel: "mid", education: "Hospitality degree", categoryId: "hospitality",
    skills: ["Guest Relations", "Team Leadership"], postedAt: "2026-06-27", isUrgent: false, isAccessible: false,
    isVisaSponsorship: false, isAiJob: false, description: "Lead front-of-house operations for a boutique hotel group.",
  },
  {
    id: "job-010", title: "Cybersecurity Analyst", companyId: "shieldpoint-security", companyName: "ShieldPoint Security", companyLogoColor: "#ef4444",
    location: "Riyadh, Saudi Arabia", country: "Saudi Arabia", city: "Riyadh", salaryMin: 90000, salaryMax: 120000, currency: "SAR",
    type: "full-time", workMode: "hybrid", experienceLevel: "mid", education: "Bachelor's degree", categoryId: "security",
    skills: ["SIEM", "Threat Detection", "Incident Response"], postedAt: "2026-06-24", isUrgent: true, isAccessible: false,
    isVisaSponsorship: true, isAiJob: false, description: "Monitor and respond to security incidents across enterprise infrastructure.",
  },
  {
    id: "job-011", title: "AI Prompt Engineer", companyId: "vertex-ai-labs", companyName: "Vertex AI Labs", companyLogoColor: "#a855f7",
    location: "Remote", country: "Remote", city: "Remote", salaryMin: 70000, salaryMax: 95000, currency: "USD",
    type: "contract", workMode: "remote", experienceLevel: "mid", education: "Not required", categoryId: "ai",
    skills: ["Prompt Design", "LLMs", "Evaluation"], postedAt: "2026-07-01", isUrgent: true, isAccessible: true,
    isVisaSponsorship: false, isAiJob: true, description: "Design and evaluate prompts and agent workflows for our LLM products.",
  },
  {
    id: "job-012", title: "Junior Backend Developer", companyId: "nova-systems", companyName: "Nova Systems", companyLogoColor: "#6366f1",
    location: "Austin, USA", country: "United States", city: "Austin", salaryMin: 65000, salaryMax: 80000, currency: "USD",
    type: "full-time", workMode: "hybrid", experienceLevel: "entry", education: "Bachelor's degree", categoryId: "technology",
    skills: ["Node.js", "PostgreSQL"], postedAt: "2026-06-26", isUrgent: false, isAccessible: true,
    isVisaSponsorship: false, isAiJob: false, description: "Build reliable backend services for our marketplace platform.",
  },
  {
    id: "job-013", title: "Content Marketing Specialist", companyId: "clearview-design", companyName: "Clearview Design Studio", companyLogoColor: "#ec4899",
    location: "Remote", country: "Remote", city: "Remote", salaryMin: 48000, salaryMax: 62000, currency: "USD",
    type: "part-time", workMode: "remote", experienceLevel: "mid", education: "Not required", categoryId: "marketing",
    skills: ["SEO", "Copywriting"], postedAt: "2026-06-19", isUrgent: false, isAccessible: true,
    isVisaSponsorship: false, isAiJob: false, description: "Plan and produce content campaigns for our design clients.",
  },
  {
    id: "job-014", title: "Legal Counsel — Immigration", companyId: "atlas-finance", companyName: "Atlas Finance Group", companyLogoColor: "#0ea5e9",
    location: "London, UK", country: "United Kingdom", city: "London", salaryMin: 72000, salaryMax: 95000, currency: "GBP",
    type: "full-time", workMode: "onsite", experienceLevel: "senior", education: "Law degree", categoryId: "legal",
    skills: ["Immigration Law", "Compliance"], postedAt: "2026-06-14", isUrgent: false, isAccessible: false,
    isVisaSponsorship: true, isAiJob: false, description: "Advise on visa sponsorship and cross-border employment compliance.",
  },
  {
    id: "job-015", title: "Customer Support Specialist", companyId: "nova-systems", companyName: "Nova Systems", companyLogoColor: "#6366f1",
    location: "Remote", country: "Remote", city: "Remote", salaryMin: 38000, salaryMax: 48000, currency: "USD",
    type: "full-time", workMode: "remote", experienceLevel: "entry", education: "Not required", categoryId: "customerSupport",
    skills: ["Zendesk", "Communication"], postedAt: "2026-07-02", isUrgent: true, isAccessible: true,
    isVisaSponsorship: false, isAiJob: false, description: "Help customers succeed with our platform via chat and email support. Screen-reader friendly tooling.",
  },
  {
    id: "job-016", title: "Structural Engineer", companyId: "orbit-manufacturing", companyName: "Orbit Manufacturing Co.", companyLogoColor: "#f97316",
    location: "Osaka, Japan", country: "Japan", city: "Osaka", salaryMin: 5800000, salaryMax: 7200000, currency: "JPY",
    type: "full-time", workMode: "onsite", experienceLevel: "senior", education: "Engineering degree", categoryId: "construction",
    skills: ["AutoCAD", "Structural Analysis"], postedAt: "2026-06-16", isUrgent: false, isAccessible: false,
    isVisaSponsorship: true, isAiJob: false, description: "Lead structural design for large-scale industrial construction projects.",
  },
  {
    id: "job-017", title: "Translator (Arabic-English)", companyId: "summit-education", companyName: "Summit Education Group", companyLogoColor: "#14b8a6",
    location: "Remote", country: "Remote", city: "Remote", salaryMin: 35000, salaryMax: 50000, currency: "USD",
    type: "freelance", workMode: "remote", experienceLevel: "mid", education: "Not required", categoryId: "translation",
    skills: ["Arabic", "English", "Localization"], postedAt: "2026-06-21", isUrgent: false, isAccessible: true,
    isVisaSponsorship: false, isAiJob: false, description: "Translate educational content between Arabic and English with cultural accuracy.",
  },
  {
    id: "job-018", title: "DevOps Intern", companyId: "vertex-ai-labs", companyName: "Vertex AI Labs", companyLogoColor: "#a855f7",
    location: "Berlin, Germany", country: "Germany", city: "Berlin", salaryMin: 24000, salaryMax: 30000, currency: "EUR",
    type: "internship", workMode: "hybrid", experienceLevel: "entry", education: "Currently studying", categoryId: "technology",
    skills: ["Docker", "CI/CD"], postedAt: "2026-06-30", isUrgent: false, isAccessible: false,
    isVisaSponsorship: true, isAiJob: false, description: "Support our infrastructure team with deployment automation over a 6-month internship.",
  },
  {
    id: "job-019", title: "Government Policy Analyst", companyId: "atlas-finance", companyName: "Atlas Finance Group", companyLogoColor: "#0ea5e9",
    location: "Ottawa, Canada", country: "Canada", city: "Ottawa", salaryMin: 62000, salaryMax: 78000, currency: "CAD",
    type: "full-time", workMode: "onsite", experienceLevel: "mid", education: "Master's degree", categoryId: "government",
    skills: ["Policy Research", "Public Affairs"], postedAt: "2026-06-17", isUrgent: false, isAccessible: true,
    isVisaSponsorship: false, isAiJob: false, description: "Research and draft policy recommendations for economic development programs.",
  },
  {
    id: "job-020", title: "Startup Growth Lead", companyId: "clearview-design", companyName: "Clearview Design Studio", companyLogoColor: "#ec4899",
    location: "Remote", country: "Remote", city: "Remote", salaryMin: 80000, salaryMax: 110000, currency: "USD",
    type: "full-time", workMode: "remote", experienceLevel: "senior", education: "Not required", categoryId: "startupJobs",
    skills: ["Growth Strategy", "Analytics"], postedAt: "2026-07-01", isUrgent: true, isAccessible: false,
    isVisaSponsorship: false, isAiJob: false, description: "Own acquisition and retention strategy for an early-stage design startup.",
  },
];
