import {
  Cpu,
  BrainCircuit,
  HeartPulse,
  Wrench,
  GraduationCap,
  Landmark,
  Megaphone,
  Handshake,
  Headphones,
  Palette,
  PenTool,
  Languages,
  Scale,
  Building2,
  ShieldCheck,
  Factory,
  UtensilsCrossed,
  Plane,
  Truck,
  HardHat,
  Globe,
  Accessibility,
  BadgeCheck,
  Laptop,
  Rocket,
} from "lucide-react";
import type { Category } from "./types";

export const CAREER_CATEGORIES: Category[] = [
  { id: "technology", labelKey: "careersPage.category.technology", icon: Cpu, jobCount: 4218 },
  { id: "ai", labelKey: "careersPage.category.ai", icon: BrainCircuit, jobCount: 1342 },
  { id: "healthcare", labelKey: "careersPage.category.healthcare", icon: HeartPulse, jobCount: 2870 },
  { id: "engineering", labelKey: "careersPage.category.engineering", icon: Wrench, jobCount: 3106 },
  { id: "education", labelKey: "careersPage.category.education", icon: GraduationCap, jobCount: 1590 },
  { id: "finance", labelKey: "careersPage.category.finance", icon: Landmark, jobCount: 2245 },
  { id: "marketing", labelKey: "careersPage.category.marketing", icon: Megaphone, jobCount: 1877 },
  { id: "sales", labelKey: "careersPage.category.sales", icon: Handshake, jobCount: 2530 },
  { id: "customerSupport", labelKey: "careersPage.category.customerSupport", icon: Headphones, jobCount: 1420 },
  { id: "design", labelKey: "careersPage.category.design", icon: Palette, jobCount: 1685 },
  { id: "writing", labelKey: "careersPage.category.writing", icon: PenTool, jobCount: 742 },
  { id: "translation", labelKey: "careersPage.category.translation", icon: Languages, jobCount: 398 },
  { id: "legal", labelKey: "careersPage.category.legal", icon: Scale, jobCount: 611 },
  { id: "government", labelKey: "careersPage.category.government", icon: Building2, jobCount: 954 },
  { id: "security", labelKey: "careersPage.category.security", icon: ShieldCheck, jobCount: 1108 },
  { id: "manufacturing", labelKey: "careersPage.category.manufacturing", icon: Factory, jobCount: 1793 },
  { id: "hospitality", labelKey: "careersPage.category.hospitality", icon: UtensilsCrossed, jobCount: 1256 },
  { id: "tourism", labelKey: "careersPage.category.tourism", icon: Plane, jobCount: 683 },
  { id: "logistics", labelKey: "careersPage.category.logistics", icon: Truck, jobCount: 1467 },
  { id: "construction", labelKey: "careersPage.category.construction", icon: HardHat, jobCount: 1329 },
  { id: "remoteJobs", labelKey: "careersPage.category.remoteJobs", icon: Globe, jobCount: 5240 },
  { id: "accessibleJobs", labelKey: "careersPage.category.accessibleJobs", icon: Accessibility, jobCount: 862 },
  { id: "visaSponsorship", labelKey: "careersPage.category.visaSponsorship", icon: BadgeCheck, jobCount: 974 },
  { id: "freelance", labelKey: "careersPage.category.freelance", icon: Laptop, jobCount: 2108 },
  { id: "startupJobs", labelKey: "careersPage.category.startupJobs", icon: Rocket, jobCount: 1531 },
];
