apiVersion: v1
kind: Namespace
metadata:
  name: visionex-tv
  labels:
    app.kubernetes.io/part-of: visionex-tv
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: visionex-monitoring
  labels:
    app.kubernetes.io/part-of: visionex-tv
