import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

new_keys = {
    'ar': {
        'ptool.pageTitle': 'الأدوات الاحترافية',
        'ptool.balance': 'رصيدك:',
        'ptool.enoughFor': 'يكفي لـ',
        'ptool.tools': 'أداة',
        'ptool.loginPrompt': 'سجّل دخولك للشراء',
        'ptool.login': 'تسجيل الدخول',
        'ptool.owned': 'مشترى',
        'ptool.viewDetails': 'عرض التفاصيل',
        'ptool.note': 'ملاحظة',
        'ptool.noteDesc': 'جميع الأدوات مصممة لـ Windows وتعمل كملفات .bat. بعض الأدوات تحتاج تشغيلها كمسؤول. بمجرد الشراء يمكنك تحميل الأداة في أي وقت.',
        'tool.loginRequired': 'يجب تسجيل الدخول',
        'tool.purchased': 'تم الشراء!',
        'tool.vxDeducted': 'تم خصم {vx} VX',
        'tool.features': 'المميزات',
        'tool.howToUse': 'كيفية الاستخدام',
        'tool.step1': 'اشترِ الأداة بالنقر على زر الشراء',
        'tool.step2': 'سيتم تحميل ملف .bat تلقائياً',
        'tool.step3Admin': 'شغّل الملف كمسؤول (Run as Administrator)',
        'tool.step3': 'شغّل الملف بالضغط عليه مرتين',
        'tool.step4': 'انتظر حتى تكتمل العملية',
        'tool.alreadyPurchased': 'مشترى بالفعل',
        'tool.oneTimePurchase': 'شراء مرة واحدة',
        'tool.balance': 'رصيدك:',
        'tool.processing': 'جاري...',
        'tool.downloadFree': 'تحميل مجاناً',
        'tool.buyDownload': 'اشترِ وحمّل',
        'tool.loginToPurchase': 'سجّل دخولك للشراء',
        'tool.needMoreVX': 'تحتاج {vx} VX إضافية',
        'tool.redownloadNote': 'بعد الشراء يمكنك التحميل في أي وقت',
        'tool.relatedTools': 'أدوات مشابهة',
    },
    'de': {
        'ptool.pageTitle': 'Professionelle Werkzeuge',
        'ptool.balance': 'Dein Guthaben:',
        'ptool.enoughFor': 'reicht für',
        'ptool.tools': 'Werkzeuge',
        'ptool.loginPrompt': 'Einloggen zum Kaufen',
        'ptool.login': 'Anmelden',
        'ptool.owned': 'Gekauft',
        'ptool.viewDetails': 'Details anzeigen',
        'ptool.note': 'Hinweis',
        'ptool.noteDesc': 'Alle Werkzeuge sind für Windows entwickelt und laufen als .bat-Dateien. Einige erfordern Administratorrechte. Nach dem Kauf kannst du jederzeit erneut herunterladen.',
        'tool.loginRequired': 'Anmeldung erforderlich',
        'tool.purchased': 'Gekauft!',
        'tool.vxDeducted': '{vx} VX abgezogen',
        'tool.features': 'Funktionen',
        'tool.howToUse': 'Verwendung',
        'tool.step1': 'Kaufe das Werkzeug mit dem Kaufen-Button',
        'tool.step2': 'Eine .bat-Datei wird automatisch heruntergeladen',
        'tool.step3Admin': 'Datei als Administrator ausfuehren (Rechtsklick -> Als Admin ausfuehren)',
        'tool.step3': 'Doppelklick auf die Datei zum Ausfuehren',
        'tool.step4': 'Warte bis der Vorgang abgeschlossen ist',
        'tool.alreadyPurchased': 'Bereits gekauft',
        'tool.oneTimePurchase': 'Einmaliger Kauf',
        'tool.balance': 'Guthaben:',
        'tool.processing': 'Wird verarbeitet...',
        'tool.downloadFree': 'Kostenlos herunterladen',
        'tool.buyDownload': 'Kaufen & Herunterladen',
        'tool.loginToPurchase': 'Anmelden zum Kaufen',
        'tool.needMoreVX': '{vx} VX mehr benoetigt',
        'tool.redownloadNote': 'Nach dem Kauf jederzeit erneut herunterladen',
        'tool.relatedTools': 'Aehnliche Werkzeuge',
    },
    'es': {
        'ptool.pageTitle': 'Herramientas Profesionales',
        'ptool.balance': 'Tu saldo:',
        'ptool.enoughFor': 'suficiente para',
        'ptool.tools': 'herramientas',
        'ptool.loginPrompt': 'Inicia sesion para comprar',
        'ptool.login': 'Iniciar sesion',
        'ptool.owned': 'Comprado',
        'ptool.viewDetails': 'Ver detalles',
        'ptool.note': 'Nota',
        'ptool.noteDesc': 'Todas las herramientas estan disenadas para Windows y se ejecutan como archivos .bat. Algunas requieren ejecutar como Administrador. Una vez comprado, puedes volver a descargar en cualquier momento.',
        'tool.loginRequired': 'Inicio de sesion requerido',
        'tool.purchased': 'Comprado!',
        'tool.vxDeducted': '{vx} VX deducidos',
        'tool.features': 'Caracteristicas',
        'tool.howToUse': 'Como usar',
        'tool.step1': 'Compra la herramienta haciendo clic en el boton de compra',
        'tool.step2': 'Un archivo .bat se descargara automaticamente',
        'tool.step3Admin': 'Ejecuta el archivo como Administrador (clic derecho -> Ejecutar como Admin)',
        'tool.step3': 'Haz doble clic en el archivo para ejecutarlo',
        'tool.step4': 'Espera a que se complete la operacion',
        'tool.alreadyPurchased': 'Ya comprado',
        'tool.oneTimePurchase': 'Compra unica',
        'tool.balance': 'Saldo:',
        'tool.processing': 'Procesando...',
        'tool.downloadFree': 'Descargar gratis',
        'tool.buyDownload': 'Comprar y descargar',
        'tool.loginToPurchase': 'Iniciar sesion para comprar',
        'tool.needMoreVX': 'Necesitas {vx} VX mas',
        'tool.redownloadNote': 'Vuelve a descargar en cualquier momento despues de comprar',
        'tool.relatedTools': 'Herramientas relacionadas',
    },
    'fr': {
        'ptool.pageTitle': 'Outils Professionnels',
        'ptool.balance': 'Votre solde :',
        'ptool.enoughFor': 'suffisant pour',
        'ptool.tools': 'outils',
        'ptool.loginPrompt': 'Connectez-vous pour acheter',
        'ptool.login': 'Connexion',
        'ptool.owned': 'Achete',
        'ptool.viewDetails': 'Voir les details',
        'ptool.note': 'Note',
        'ptool.noteDesc': 'Tous les outils sont concus pour Windows et executent en tant que fichiers .bat. Certains necessitent des droits Administrateur. Une fois achete, vous pouvez re-telecharger a tout moment.',
        'tool.loginRequired': 'Connexion requise',
        'tool.purchased': 'Achete !',
        'tool.vxDeducted': '{vx} VX deduits',
        'tool.features': 'Fonctionnalites',
        'tool.howToUse': 'Comment utiliser',
        'tool.step1': "Achetez l'outil en cliquant sur le bouton d'achat",
        'tool.step2': 'Un fichier .bat sera telecharge automatiquement',
        'tool.step3Admin': "Executez le fichier en tant qu'Administrateur",
        'tool.step3': "Double-cliquez sur le fichier pour l'executer",
        'tool.step4': "Attendez la fin de l'operation",
        'tool.alreadyPurchased': 'Deja achete',
        'tool.oneTimePurchase': 'Achat unique',
        'tool.balance': 'Solde :',
        'tool.processing': 'En cours...',
        'tool.downloadFree': 'Telecharger gratuitement',
        'tool.buyDownload': 'Acheter et telecharger',
        'tool.loginToPurchase': 'Se connecter pour acheter',
        'tool.needMoreVX': 'Il vous faut {vx} VX de plus',
        'tool.redownloadNote': 'Re-telechargez a tout moment apres achat',
        'tool.relatedTools': 'Outils connexes',
    },
    'pt': {
        'ptool.pageTitle': 'Ferramentas Profissionais',
        'ptool.balance': 'Seu saldo:',
        'ptool.enoughFor': 'suficiente para',
        'ptool.tools': 'ferramentas',
        'ptool.loginPrompt': 'Faca login para comprar',
        'ptool.login': 'Entrar',
        'ptool.owned': 'Comprado',
        'ptool.viewDetails': 'Ver detalhes',
        'ptool.note': 'Nota',
        'ptool.noteDesc': 'Todas as ferramentas sao projetadas para Windows e executam como arquivos .bat. Algumas exigem execucao como Administrador. Apos a compra, voce pode baixar novamente a qualquer momento.',
        'tool.loginRequired': 'Login necessario',
        'tool.purchased': 'Comprado!',
        'tool.vxDeducted': '{vx} VX deduzidos',
        'tool.features': 'Recursos',
        'tool.howToUse': 'Como usar',
        'tool.step1': 'Compre a ferramenta clicando no botao de compra',
        'tool.step2': 'Um arquivo .bat sera baixado automaticamente',
        'tool.step3Admin': 'Execute o arquivo como Administrador',
        'tool.step3': 'Clique duas vezes no arquivo para executa-lo',
        'tool.step4': 'Aguarde a conclusao da operacao',
        'tool.alreadyPurchased': 'Ja comprado',
        'tool.oneTimePurchase': 'Compra unica',
        'tool.balance': 'Saldo:',
        'tool.processing': 'Processando...',
        'tool.downloadFree': 'Baixar gratuitamente',
        'tool.buyDownload': 'Comprar e baixar',
        'tool.loginToPurchase': 'Fazer login para comprar',
        'tool.needMoreVX': 'Precisa de {vx} VX a mais',
        'tool.redownloadNote': 'Baixe novamente a qualquer momento apos a compra',
        'tool.relatedTools': 'Ferramentas relacionadas',
    },
    'ru': {
        'ptool.pageTitle': 'Профессиональные инструменты',
        'ptool.balance': 'Ваш баланс:',
        'ptool.enoughFor': 'хватит на',
        'ptool.tools': 'инструментов',
        'ptool.loginPrompt': 'Войдите для покупки',
        'ptool.login': 'Войти',
        'ptool.owned': 'Куплено',
        'ptool.viewDetails': 'Подробнее',
        'ptool.note': 'Примечание',
        'ptool.noteDesc': 'Все инструменты созданы для Windows и работают как .bat-файлы. Некоторые требуют прав Администратора. После покупки можно скачивать в любое время.',
        'tool.loginRequired': 'Требуется вход',
        'tool.purchased': 'Куплено!',
        'tool.vxDeducted': '{vx} VX списано',
        'tool.features': 'Возможности',
        'tool.howToUse': 'Как использовать',
        'tool.step1': 'Купите инструмент, нажав кнопку покупки',
        'tool.step2': 'Файл .bat будет загружен автоматически',
        'tool.step3Admin': 'Запустите файл от имени Администратора',
        'tool.step3': 'Дважды щёлкните файл для запуска',
        'tool.step4': 'Дождитесь завершения операции',
        'tool.alreadyPurchased': 'Уже куплено',
        'tool.oneTimePurchase': 'Разовая покупка',
        'tool.balance': 'Баланс:',
        'tool.processing': 'Обработка...',
        'tool.downloadFree': 'Скачать бесплатно',
        'tool.buyDownload': 'Купить и скачать',
        'tool.loginToPurchase': 'Войдите для покупки',
        'tool.needMoreVX': 'Нужно ещё {vx} VX',
        'tool.redownloadNote': 'Скачивайте повторно в любое время после покупки',
        'tool.relatedTools': 'Похожие инструменты',
    },
    'tr': {
        'ptool.pageTitle': 'Profesyonel Araclar',
        'ptool.balance': 'Bakiyeniz:',
        'ptool.enoughFor': 'yeterli',
        'ptool.tools': 'arac',
        'ptool.loginPrompt': 'Satin almak icin giris yapin',
        'ptool.login': 'Giris',
        'ptool.owned': 'Satin alindi',
        'ptool.viewDetails': 'Detaylari goruntule',
        'ptool.note': 'Not',
        'ptool.noteDesc': 'Tum araclar Windows icin tasarlanmis .bat dosyalari olarak calisir. Bazi araclar Yonetici olarak calistirilmalidir. Satin aldiktan sonra istediginiz zaman yeniden indirebilirsiniz.',
        'tool.loginRequired': 'Giris gerekli',
        'tool.purchased': 'Satin alindi!',
        'tool.vxDeducted': '{vx} VX dusuldu',
        'tool.features': 'Ozellikler',
        'tool.howToUse': 'Nasil kullanilir',
        'tool.step1': 'Satin al dugmesine tiklayarak araci satin alin',
        'tool.step2': 'Bir .bat dosyasi otomatik olarak indirilecektir',
        'tool.step3Admin': 'Dosyayi Yonetici olarak calistirin',
        'tool.step3': 'Calistirmak icin dosyaya cift tiklayin',
        'tool.step4': 'Islem tamamlanana kadar bekleyin',
        'tool.alreadyPurchased': 'Zaten satin alindi',
        'tool.oneTimePurchase': 'Tek seferlik satin alma',
        'tool.balance': 'Bakiye:',
        'tool.processing': 'Isleniyor...',
        'tool.downloadFree': 'Ucretsiz indir',
        'tool.buyDownload': 'Satin al ve indir',
        'tool.loginToPurchase': 'Satin almak icin giris yapin',
        'tool.needMoreVX': '{vx} VX daha gerekiyor',
        'tool.redownloadNote': 'Satin aldiktan sonra istediginiz zaman yeniden indirin',
        'tool.relatedTools': 'Ilgili araclar',
    },
    'zh': {
        'ptool.pageTitle': '专业工具',
        'ptool.balance': '您的余额：',
        'ptool.enoughFor': '足够购买',
        'ptool.tools': '件工具',
        'ptool.loginPrompt': '登录购买',
        'ptool.login': '登录',
        'ptool.owned': '已购买',
        'ptool.viewDetails': '查看详情',
        'ptool.note': '注意',
        'ptool.noteDesc': '所有工具均为Windows设计，以.bat文件运行。部分工具需要以管理员身份运行。购买后可随时重新下载。',
        'tool.loginRequired': '需要登录',
        'tool.purchased': '已购买！',
        'tool.vxDeducted': '已扣除 {vx} VX',
        'tool.features': '功能特点',
        'tool.howToUse': '使用方法',
        'tool.step1': '点击购买按钮购买工具',
        'tool.step2': '将自动下载一个.bat文件',
        'tool.step3Admin': '以管理员身份运行文件',
        'tool.step3': '双击文件运行',
        'tool.step4': '等待操作完成',
        'tool.alreadyPurchased': '已购买',
        'tool.oneTimePurchase': '一次性购买',
        'tool.balance': '余额：',
        'tool.processing': '处理中...',
        'tool.downloadFree': '免费下载',
        'tool.buyDownload': '购买并下载',
        'tool.loginToPurchase': '登录购买',
        'tool.needMoreVX': '还需要 {vx} VX',
        'tool.redownloadNote': '购买后可随时重新下载',
        'tool.relatedTools': '相关工具',
    },
}

anchor = '"svcReq.successToast":'

for lang, keys in new_keys.items():
    path = f'src/i18n/{lang}.ts'
    with open(path, encoding='utf-8') as f:
        content = f.read()

    lines_to_add = []
    for k, v in keys.items():
        if f'"{k}"' not in content:
            escaped = v.replace('"', '\\"')
            lines_to_add.append(f'  "{k}": "{escaped}",')

    if not lines_to_add:
        print(f'  SKIP {lang} (all keys exist)')
        continue

    block = '\n' + '\n'.join(lines_to_add)
    idx = content.find(anchor)
    if idx == -1:
        print(f'  ERROR {lang}: anchor not found')
        continue
    end = content.index('\n', idx) + 1
    content = content[:end] + block + '\n' + content[end:]

    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'  DONE {lang}: +{len(lines_to_add)} keys')

print('All done.')
