import quizImg from "@/assets/arcade/game-quiz-premium-v1.webp";
import memoryImg from "@/assets/arcade/game-memory-premium-v1.webp";
import wordImg from "@/assets/arcade/game-word-puzzle-premium-v1.webp";
import hangmanImg from "@/assets/arcade/game-hangman-premium-v1.webp";
import jungleImg from "@/assets/arcade/game-jungle-survival-premium-v1.webp";
import starchefImg from "@/assets/arcade/game-star-chef-premium-v1.webp";
import unoImg from "@/assets/arcade/game-uno-ultra-premium-v1.webp";
import neonbreachImg from "@/assets/arcade/game-neon-breach-premium-v1.webp";
import logiquestImg from "@/assets/arcade/game-logiquest-premium-v1.webp";
import tradetycoonImg from "@/assets/arcade/game-trade-tycoon-premium-v1.webp";
import tacticalImg from "@/assets/arcade/game-tactical-strike-premium-v1.webp";
import dominoesImg from "@/assets/arcade/game-dominoes-premium-v1.webp";
import farkleImg from "@/assets/arcade/game-farkle-premium-v1.webp";
import briscolaImg from "@/assets/arcade/game-briscola-premium-v1.webp";
import card99Img from "@/assets/arcade/game-card-99-premium-v1.webp";
import dreamhomeImg from "@/assets/arcade/game-dream-home-premium-v1.webp";
import laptoptechImg from "@/assets/arcade/game-laptop-tech-premium-v1.webp";
import earmasterImg from "@/assets/arcade/game-music-ear-premium-v1.webp";
import fashionImg from "@/assets/arcade/game-fashion-designer-premium-v1.webp";
import velocityImg from "@/assets/arcade/game-velocity-premium-v1.webp";
import visionopolyImg from "@/assets/game-visionopoly.svg";
import akinatorImg from "@/assets/arcade/game-akinator-premium-v1.webp";
import game2048Img from "@/assets/arcade/game-2048-v1.svg";
import minesweeperImg from "@/assets/arcade/game-minesweeper-v1.svg";
import connectFourImg from "@/assets/arcade/game-connect-four-v1.svg";
import reactionTestImg from "@/assets/arcade/game-reaction-test-v1.svg";
import ticTacToeImg from "@/assets/arcade/game-tic-tac-toe-v1.svg";
import typingSpeedImg from "@/assets/arcade/game-typing-speed-v1.svg";
import mathChallengeImg from "@/assets/arcade/game-math-challenge-v1.svg";
import simonSaysImg from "@/assets/arcade/game-simon-says-v1.svg";
import blindMazeImg from "@/assets/arcade/game-blind-maze-v1.svg";
import chessImg from "@/assets/arcade/game-chess-premium-v2.webp";
import backgammonImg from "@/assets/arcade/game-backgammon-premium-v2.webp";
import ludoImg from "@/assets/arcade/game-ludo-premium-v2.webp";
import wordMasterImg from "@/assets/arcade/game-wordmaster-v1.svg";
import skyboundImg from "@/assets/arcade/game-skybound-quest-premium-v2.webp";
import penaltyShootoutImg from "@/assets/arcade/game-penalty-shootout-premium-v2.webp";
import basketballChallengeImg from "@/assets/arcade/game-basketball-challenge-premium-v2.webp";
import airHockeyImg from "@/assets/arcade/game-air-hockey-premium-v2.webp";
import tableTennisImg from "@/assets/arcade/game-table-tennis-premium-v2.webp";
import bowlingImg from "@/assets/arcade/game-bowling-premium-v2.webp";
import miniGolfImg from "@/assets/arcade/game-mini-golf-premium-v2.webp";

export const ARCADE_CATEGORIES = ["Classic","Puzzle","Board","Card","Educational","Kids","Typing","Memory","Word","Math","Logic","Quiz","Reaction","Arcade","Action","Adventure","Platform","Racing","Sports","Physics","Simulation","Idle","Strategy","Tower Defense","City Builder","Business Simulation","Cooking","Music","Drawing","Accessible","Audio","Multiplayer"] as const;
export type ArcadeCategory = typeof ARCADE_CATEGORIES[number];
export type ArcadeDifficulty = "Easy" | "Medium" | "Hard";
export type ArcadeAge = "Everyone" | "Kids" | "Teens";

export interface ArcadeGame {
  slug: string;
  to: string;
  image: string;
  title: string;
  titleAr: string;
  description: string;
  descriptionAr: string;
  categories: ArcadeCategory[];
  difficulty: ArcadeDifficulty;
  age: ArcadeAge;
  players: string;
  plays: number;
  rating: number;
  featured?: boolean;
  trending?: boolean;
  recentlyAdded?: boolean;
  controls: string[];
  accessible: boolean;
}

const game = (data: ArcadeGame) => data;

export const ARCADE_GAMES: ArcadeGame[] = [
  game({ slug:"quiz-challenge", to:"/games/quiz-challenge", image:quizImg, title:"Quiz Challenge", titleAr:"تحدي المعلومات", description:"Fast questions, smart choices, and competitive rounds.", descriptionAr:"أسئلة سريعة وخيارات ذكية وجولات تنافسية.", categories:["Puzzle","Educational","Multiplayer","Accessible"], difficulty:"Medium", age:"Everyone", players:"1–2", plays:0, rating:0, featured:true, trending:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"memory", to:"/games/memory", image:memoryImg, title:"Memory Game", titleAr:"لعبة الذاكرة", description:"Match every pair while sharpening focus and recall.", descriptionAr:"طابق الأزواج وطوّر التركيز والذاكرة.", categories:["Puzzle","Educational","Kids","Accessible"], difficulty:"Easy", age:"Kids", players:"1", plays:0, rating:0, featured:true, controls:["Keyboard","Touch","Voice prompts"], accessible:true }),
  game({ slug:"word-puzzle", to:"/games/word-puzzle", image:wordImg, title:"Word Puzzle", titleAr:"لغز الكلمات", description:"Build words, expand vocabulary, and beat the clock.", descriptionAr:"كوّن الكلمات ووسّع مفرداتك وتحدَّ الوقت.", categories:["Puzzle","Educational","Kids","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, trending:true, controls:["Keyboard","Touch","Voice prompts"], accessible:true }),
  game({ slug:"hangman", to:"/games/hangman", image:hangmanImg, title:"Hangman", titleAr:"الرجل المشنوق", description:"Reveal the hidden word before your guesses run out.", descriptionAr:"اكتشف الكلمة المخفية قبل نفاد المحاولات.", categories:["Puzzle","Educational","Classic","Multiplayer"], difficulty:"Medium", age:"Everyone", players:"1–2", plays:0, rating:0, controls:["Keyboard","Touch"], accessible:false }),
  game({ slug:"akinator", to:"/games/akinator", image:akinatorImg, title:"Akinator", titleAr:"أكيناتور", description:"Answer clever questions and challenge the guessing engine.", descriptionAr:"أجب عن أسئلة ذكية وتحدَّ محرك التخمين.", categories:["Puzzle","Kids"], difficulty:"Easy", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:false }),
  game({ slug:"jungle-survival", to:"/games/jungle-survival", image:jungleImg, title:"Jungle Survival", titleAr:"النجاة في الأدغال", description:"Make the right survival choices in a living jungle.", descriptionAr:"اتخذ قرارات النجاة الصحيحة داخل الأدغال.", categories:["Action","Strategy","Multiplayer"], difficulty:"Hard", age:"Teens", players:"1–2", plays:0, rating:0, trending:true, controls:["Keyboard","Touch"], accessible:false }),
  game({ slug:"neon-breach", to:"/games/neon-breach", image:neonbreachImg, title:"Neon Breach", titleAr:"اختراق النيون", description:"Decode luminous sequences and break the firewall.", descriptionAr:"فك تسلسلات النيون واخترق جدار الحماية.", categories:["Action","Puzzle","Multiplayer"], difficulty:"Hard", age:"Teens", players:"1–2", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:false }),
  game({ slug:"tactical-strike", to:"/games/tactical-strike", image:tacticalImg, title:"Tactical Strike", titleAr:"الضربة التكتيكية", description:"Plan each move and hit the right tactical target.", descriptionAr:"خطط لكل حركة وأصب الهدف التكتيكي الصحيح.", categories:["Action","Strategy","Multiplayer"], difficulty:"Hard", age:"Teens", players:"1–2", plays:0, rating:0, controls:["Keyboard","Touch"], accessible:false }),
  game({ slug:"velocity-racing", to:"/games/velocity-racing", image:velocityImg, title:"Velocity X Racing", titleAr:"سباق Velocity X", description:"React fast, master the track, and chase the podium.", descriptionAr:"تفاعل بسرعة وسيطر على الحلبة وطارد منصة الفوز.", categories:["Action","Multiplayer"], difficulty:"Hard", age:"Everyone", players:"1–2", plays:0, rating:0, featured:true, trending:true, controls:["Arrow keys","Touch"], accessible:false }),
  game({ slug:"star-chef", to:"/games/star-chef", image:starchefImg, title:"Star Chef", titleAr:"الطاهي النجم", description:"Read the order, choose ingredients, and plate it perfectly.", descriptionAr:"اقرأ الطلب واختر المكونات وقدّم الطبق بإتقان.", categories:["Educational","Kids","Multiplayer"], difficulty:"Medium", age:"Kids", players:"1–2", plays:0, rating:0, controls:["Keyboard","Touch"], accessible:false }),
  game({ slug:"dream-home", to:"/games/dream-home", image:dreamhomeImg, title:"Dream Home", titleAr:"منزل الأحلام", description:"Design welcoming rooms and complete every brief.", descriptionAr:"صمم غرفاً جميلة وأنجز كل تحدٍ.", categories:["Strategy","Kids"], difficulty:"Easy", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:false }),
  game({ slug:"music-ear", to:"/games/music-ear", image:earmasterImg, title:"Music Ear Master", titleAr:"خبير الأذن الموسيقية", description:"Train your ear to identify notes with precision.", descriptionAr:"درّب أذنك على تمييز النغمات بدقة.", categories:["Educational","Accessible","Multiplayer"], difficulty:"Medium", age:"Everyone", players:"1–2", plays:0, rating:0, featured:true, controls:["Keyboard","Audio","Touch"], accessible:true }),
  game({ slug:"fashion-designer", to:"/games/fashion-designer", image:fashionImg, title:"Fashion Designer", titleAr:"مصمم الأزياء", description:"Combine fabric, color, and style for every occasion.", descriptionAr:"ادمج القماش واللون والأسلوب لكل مناسبة.", categories:["Strategy","Kids"], difficulty:"Easy", age:"Everyone", players:"1", plays:0, rating:0, controls:["Keyboard","Touch"], accessible:false }),
  game({ slug:"uno-ultra", to:"/games/uno-ultra", image:unoImg, title:"Uno Ultra", titleAr:"أونو ألترا", description:"Match colors and numbers in a rapid card showdown.", descriptionAr:"طابق الألوان والأرقام في مواجهة ورق سريعة.", categories:["Classic","Multiplayer"], difficulty:"Easy", age:"Everyone", players:"1–2", plays:0, rating:0, trending:true, controls:["Keyboard","Touch"], accessible:false }),
  game({ slug:"dominoes", to:"/games/dominoes", image:dominoesImg, title:"Dominoes", titleAr:"الدومينو", description:"A polished classic built around smart tile placement.", descriptionAr:"لعبة كلاسيكية تعتمد على وضع الأحجار بذكاء.", categories:["Classic","Strategy","Multiplayer"], difficulty:"Medium", age:"Everyone", players:"1–2", plays:0, rating:0, controls:["Keyboard","Touch"], accessible:false }),
  game({ slug:"farkle", to:"/games/farkle", image:farkleImg, title:"Farkle", titleAr:"فاركل", description:"Push your luck, bank the dice, and build a winning score.", descriptionAr:"غامر بذكاء وثبّت النرد واجمع نقاط الفوز.", categories:["Classic","Strategy","Multiplayer"], difficulty:"Medium", age:"Everyone", players:"1–2", plays:0, rating:0, controls:["Keyboard","Touch"], accessible:false }),
  game({ slug:"briscola", to:"/games/briscola", image:briscolaImg, title:"Briscola", titleAr:"بريسكولا", description:"Master timing and tactics in the classic card game.", descriptionAr:"أتقن التوقيت والتكتيك في لعبة الورق الكلاسيكية.", categories:["Classic","Strategy","Multiplayer"], difficulty:"Hard", age:"Everyone", players:"1–2", plays:0, rating:0, controls:["Keyboard","Touch"], accessible:false }),
  game({ slug:"card-99", to:"/games/card-99", image:card99Img, title:"Card 99", titleAr:"بطاقة 99", description:"Keep the total under control and outthink your rival.", descriptionAr:"حافظ على المجموع وتفوّق على منافسك.", categories:["Classic","Strategy","Multiplayer"], difficulty:"Medium", age:"Everyone", players:"1–2", plays:0, rating:0, controls:["Keyboard","Touch"], accessible:false }),
  game({ slug:"logiquest", to:"/games/logiquest", image:logiquestImg, title:"LogiQuest", titleAr:"لوجيكويست", description:"Progress through layered logic challenges.", descriptionAr:"تقدم عبر تحديات منطقية متعددة المستويات.", categories:["Puzzle","Educational","Multiplayer"], difficulty:"Hard", age:"Everyone", players:"1–2", plays:0, rating:0, featured:true, controls:["Keyboard","Touch"], accessible:false }),
  game({ slug:"trade-tycoon", to:"/games/trade-tycoon", image:tradetycoonImg, title:"Trade Tycoon", titleAr:"إمبراطور التجارة", description:"Read the market and grow a winning trading strategy.", descriptionAr:"اقرأ السوق وابنِ استراتيجية تجارية ناجحة.", categories:["Strategy","Educational","Multiplayer"], difficulty:"Hard", age:"Teens", players:"1–2", plays:0, rating:0, controls:["Keyboard","Touch"], accessible:false }),
  game({ slug:"laptop-tech", to:"/games/laptop-tech", image:laptoptechImg, title:"Laptop Tech Master", titleAr:"خبير صيانة الحاسوب", description:"Diagnose faults and repair devices step by step.", descriptionAr:"شخّص الأعطال وأصلح الأجهزة خطوة بخطوة.", categories:["Puzzle","Educational","Multiplayer"], difficulty:"Medium", age:"Everyone", players:"1–2", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:false }),
  game({ slug:"visionopoly", to:"/games/visionopoly", image:visionopolyImg, title:"Visionopoly", titleAr:"فيجِنوبولي", description:"Build a property empire with trading, mortgages, and smart rivals.", descriptionAr:"ابنِ إمبراطورية عقارية عبر التجارة والرهن ومنافسين أذكياء.", categories:["Strategy","Classic"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, featured:true, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:false }),
  game({ slug:"2048", to:"/games/2048", image:game2048Img, title:"2048", titleAr:"٢٠٤٨", description:"Slide and combine numbered tiles in the definitive keyboard-friendly strategy puzzle.", descriptionAr:"حرّك البلاطات الرقمية وادمجها في لعبة استراتيجية متوافقة بالكامل مع لوحة المفاتيح.", categories:["Classic","Puzzle","Math","Logic","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Arrow keys","Touch controls"], accessible:true }),
  game({ slug:"minesweeper", to:"/games/minesweeper", image:minesweeperImg, title:"Minesweeper", titleAr:"كاسحة الألغام", description:"Clear a precise logic grid using number clues without triggering a mine.", descriptionAr:"استخدم الدلائل الرقمية لكشف شبكة المنطق دون تفجير أي لغم.", categories:["Classic","Puzzle","Logic","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch","Pointer"], accessible:true }),
  game({ slug:"connect-four", to:"/games/connect-four", image:connectFourImg, title:"Connect Four", titleAr:"أربعة على التوالي", description:"Build a four-disc line against a tactical computer opponent.", descriptionAr:"كوّن خطاً من أربع قطع في مواجهة خصم حاسوبي تكتيكي.", categories:["Classic","Board","Strategy","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch","Pointer"], accessible:true }),
  game({ slug:"reaction-test", to:"/games/reaction-test", image:reactionTestImg, title:"Reaction Test", titleAr:"اختبار سرعة الاستجابة", description:"Measure your response time with fair randomized signals and accessible feedback.", descriptionAr:"قس سرعة استجابتك عبر إشارات عشوائية عادلة وملاحظات صوتية واضحة.", categories:["Reaction","Arcade","Accessible"], difficulty:"Easy", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Space","Enter","Touch","Pointer"], accessible:true }),
  game({ slug:"tic-tac-toe", to:"/games/tic-tac-toe", image:ticTacToeImg, title:"Tic Tac Toe", titleAr:"إكس أو", description:"Create a three-mark line against a tactical local opponent.", descriptionAr:"كوّن خطاً من ثلاث علامات في مواجهة خصم حاسوبي تكتيكي.", categories:["Classic","Board","Strategy","Kids","Accessible"], difficulty:"Easy", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch","Pointer"], accessible:true }),
  game({ slug:"typing-speed", to:"/games/typing-speed", image:typingSpeedImg, title:"Typing Speed", titleAr:"سرعة الكتابة", description:"Measure accurate words per minute with clear keyboard-first practice.", descriptionAr:"قس سرعة الكتابة الدقيقة عبر تدريب واضح يعتمد على لوحة المفاتيح.", categories:["Typing","Educational","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard"], accessible:true }),
  game({ slug:"math-challenge", to:"/games/math-challenge", image:mathChallengeImg, title:"Math Challenge", titleAr:"تحدي الرياضيات", description:"Progress through ten adaptive arithmetic levels with instant feedback.", descriptionAr:"تقدم عبر عشرة مستويات حسابية متدرجة مع ملاحظات فورية.", categories:["Math","Educational","Kids","Accessible"], difficulty:"Medium", age:"Kids", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"simon-says", to:"/games/simon-says", image:simonSaysImg, title:"Simon Says", titleAr:"سايمون يقول", description:"Listen, remember, and reproduce increasingly long color sequences.", descriptionAr:"استمع واحفظ ثم كرر تسلسلات لونية تزداد طولاً.", categories:["Memory","Audio","Kids","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch","Audio"], accessible:true }),
  game({ slug:"trivia", to:"/games/trivia", image:quizImg, title:"Trivia", titleAr:"معلومات عامة", description:"A focused general-knowledge challenge with clear answer choices.", descriptionAr:"تحدٍ مركز للمعلومات العامة بخيارات إجابة واضحة.", categories:["Quiz","Educational","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"geography-quiz", to:"/games/geography-quiz", image:quizImg, title:"Geography Quiz", titleAr:"اختبار الجغرافيا", description:"Test capitals, continents, oceans, and world geography.", descriptionAr:"اختبر معلوماتك بالعواصم والقارات والمحيطات وجغرافيا العالم.", categories:["Quiz","Educational","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"science-quiz", to:"/games/science-quiz", image:quizImg, title:"Science Quiz", titleAr:"اختبار العلوم", description:"Explore practical questions across biology, chemistry, and physics.", descriptionAr:"استكشف أسئلة عملية في الأحياء والكيمياء والفيزياء.", categories:["Quiz","Educational","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"history-quiz", to:"/games/history-quiz", image:quizImg, title:"History Quiz", titleAr:"اختبار التاريخ", description:"Challenge your knowledge of civilizations, inventions, and world history.", descriptionAr:"اختبر معرفتك بالحضارات والاختراعات وتاريخ العالم.", categories:["Quiz","Educational","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"blind-maze", to:"/games/blind-maze", image:blindMazeImg, title:"Blind Maze", titleAr:"المتاهة الصوتية", description:"Navigate a precise maze through keyboard movement and spoken spatial feedback.", descriptionAr:"تنقل داخل متاهة دقيقة باستخدام لوحة المفاتيح والإرشاد المكاني الصوتي.", categories:["Accessible","Audio","Puzzle","Adventure"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Arrow keys","Touch","Audio"], accessible:true }),
  game({ slug:"sudoku", to:"/games/sudoku", image:logiquestImg, title:"Sudoku", titleAr:"سودوكو", description:"Complete a maintained nine-by-nine number grid with instant rule feedback.", descriptionAr:"أكمل شبكة الأرقام 9×9 مع التحقق الفوري من القواعد.", categories:["Puzzle","Logic","Math","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"nonogram", to:"/games/nonogram", image:logiquestImg, title:"Nonogram", titleAr:"نونوغرام", description:"Use row and column clues to reveal a compact logical picture.", descriptionAr:"استخدم دلائل الصفوف والأعمدة لكشف صورة منطقية.", categories:["Puzzle","Logic","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"mastermind", to:"/games/mastermind", image:logiquestImg, title:"Mastermind", titleAr:"ماسترمايند", description:"Decode a hidden four-color sequence using precise positional clues.", descriptionAr:"فك تسلسلاً مخفياً من أربعة ألوان باستخدام دلائل دقيقة.", categories:["Board","Logic","Strategy","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"word-search", to:"/games/word-search", image:wordImg, title:"Word Search", titleAr:"البحث عن الكلمات", description:"Find maintained vocabulary across an accessible letter grid.", descriptionAr:"اعثر على الكلمات داخل شبكة حروف متاحة وسهلة التنقل.", categories:["Word","Puzzle","Educational","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"color-match", to:"/games/color-match", image:reactionTestImg, title:"Color Match", titleAr:"مطابقة الألوان", description:"Respond to the displayed ink color while ignoring the written color label.", descriptionAr:"اختر لون الحبر الظاهر وتجاهل تسمية اللون المكتوبة.", categories:["Reaction","Kids","Educational","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"audio-direction", to:"/games/audio-direction", image:blindMazeImg, title:"Audio Direction", titleAr:"الاتجاه الصوتي", description:"Identify announced spatial directions across five focused rounds.", descriptionAr:"حدد الاتجاهات المكانية المعلنة عبر خمس جولات مركزة.", categories:["Audio","Accessible","Reaction"], difficulty:"Easy", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch","Audio"], accessible:true }),
  game({ slug:"reversi", to:"/games/reversi", image:dominoesImg, title:"Reversi", titleAr:"ريفيرسي", description:"Capture lines of opposing discs against a tactical computer player.", descriptionAr:"استولِ على خطوط قطع الخصم في مواجهة لاعب حاسوبي تكتيكي.", categories:["Board","Classic","Strategy","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"checkers", to:"/games/checkers", image:dominoesImg, title:"Checkers", titleAr:"الداما", description:"Move and capture across a complete keyboard-operable checkers board.", descriptionAr:"حرّك القطع والتقطها على لوحة داما متوافقة مع لوحة المفاتيح.", categories:["Board","Classic","Strategy","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"peg-solitaire", to:"/games/peg-solitaire", image:logiquestImg, title:"Peg Solitaire", titleAr:"سوليتير الأوتاد", description:"Jump pegs orthogonally until only one remains.", descriptionAr:"اقفز فوق الأوتاد أفقياً وعمودياً حتى يبقى وتد واحد.", categories:["Board","Classic","Logic","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"battleship", to:"/games/battleship", image:tacticalImg, title:"Battleship", titleAr:"السفينة الحربية", description:"Search a compact ocean grid and locate every hidden ship section.", descriptionAr:"فتش شبكة المحيط واعثر على جميع أجزاء السفن المخفية.", categories:["Board","Strategy","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"mini-golf", to:"/games/mini-golf", image:miniGolfImg, title:"Mini Golf", titleAr:"ميني غولف", description:"Calibrate power and aim across five compact skill holes.", descriptionAr:"اضبط القوة والتصويب عبر خمس حفر مهارية مصغرة.", categories:["Sports","Physics","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"bowling", to:"/games/bowling", image:bowlingImg, title:"Bowling", titleAr:"البولينغ", description:"Master release power and alignment across ten frames.", descriptionAr:"أتقن قوة الرمية والمحاذاة عبر عشر جولات.", categories:["Sports","Physics","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"archery", to:"/games/archery", image:tacticalImg, title:"Archery", titleAr:"الرماية بالقوس", description:"Balance draw power and aim over ten scored arrows.", descriptionAr:"وازن قوة السحب والتصويب عبر عشر سهام محتسبة.", categories:["Sports","Physics","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"darts", to:"/games/darts", image:tacticalImg, title:"Darts", titleAr:"السهام", description:"Target calibrated dartboard rings and sectors across nine throws.", descriptionAr:"استهدف حلقات وقطاعات لوحة السهام عبر تسع رميات.", categories:["Sports","Physics","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"airport-manager", to:"/games/airport-manager", image:laptoptechImg, title:"Airport Manager", titleAr:"مدير المطار", description:"Prioritize flights and assign runways, gates, and services safely.", descriptionAr:"حدد أولويات الرحلات ووزع المدارج والبوابات والخدمات بأمان.", categories:["Simulation","Strategy","Business Simulation","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"traffic-control", to:"/games/traffic-control", image:tacticalImg, title:"Traffic Control", titleAr:"التحكم بالمرور", description:"Coordinate queues and emergency lanes while protecting intersection safety.", descriptionAr:"نسق الطوابير ومسارات الطوارئ مع حماية سلامة التقاطع.", categories:["Simulation","Strategy","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"train-dispatcher", to:"/games/train-dispatcher", image:tradetycoonImg, title:"Train Dispatcher", titleAr:"موجّه القطارات", description:"Schedule express, commuter, freight, and rescue trains across limited tracks.", descriptionAr:"جدول القطارات السريعة والمحلية والشحن والإنقاذ عبر مسارات محدودة.", categories:["Simulation","Strategy","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"harbor-manager", to:"/games/harbor-manager", image:tradetycoonImg, title:"Harbor Manager", titleAr:"مدير الميناء", description:"Assign vessels, berths, and cargo cranes under operational deadlines.", descriptionAr:"وزع السفن والأرصفة ورافعات الشحن ضمن المهل التشغيلية.", categories:["Simulation","Strategy","Business Simulation","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"learn-letters", to:"/games/learn-letters", image:wordImg, title:"Letters Learning", titleAr:"تعلم الحروف", description:"Practice Arabic and English letters through short bilingual activities.", descriptionAr:"تدرّب على الحروف العربية والإنجليزية عبر أنشطة ثنائية اللغة.", categories:["Kids","Educational","Word","Accessible"], difficulty:"Easy", age:"Kids", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch","Audio"], accessible:true }),
  game({ slug:"learn-numbers", to:"/games/learn-numbers", image:mathChallengeImg, title:"Numbers Learning", titleAr:"تعلم الأرقام", description:"Build counting, comparison, addition, and subtraction foundations.", descriptionAr:"طوّر مهارات العد والمقارنة والجمع والطرح الأساسية.", categories:["Kids","Educational","Math","Accessible"], difficulty:"Easy", age:"Kids", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch","Audio"], accessible:true }),
  game({ slug:"learn-shapes", to:"/games/learn-shapes", image:memoryImg, title:"Shapes Learning", titleAr:"تعلم الأشكال", description:"Recognize shapes and their properties in Arabic and English.", descriptionAr:"تعرف إلى الأشكال وخصائصها بالعربية والإنجليزية.", categories:["Kids","Educational","Accessible"], difficulty:"Easy", age:"Kids", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch","Audio"], accessible:true }),
  game({ slug:"matching-studio", to:"/games/matching-studio", image:memoryImg, title:"Matching Studio", titleAr:"استوديو المطابقة", description:"Connect animals, habitats, colors, seasons, and everyday concepts.", descriptionAr:"اربط الحيوانات والموائل والألوان والفصول ومفاهيم الحياة اليومية.", categories:["Kids","Educational","Memory","Puzzle","Accessible"], difficulty:"Easy", age:"Kids", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch","Audio"], accessible:true }),
  game({ slug:"crossword", to:"/games/crossword", image:wordImg, title:"Crossword", titleAr:"الكلمات المتقاطعة", description:"Solve maintained vocabulary clues through a focused keyboard-first format.", descriptionAr:"حل دلائل المفردات ضمن تجربة مركزة تعتمد على لوحة المفاتيح.", categories:["Word","Puzzle","Educational","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"anagram-arena", to:"/games/anagram-arena", image:wordImg, title:"Anagram Arena", titleAr:"ساحة ترتيب الحروف", description:"Rearrange complete letter sets into valid alternative words.", descriptionAr:"أعد ترتيب مجموعات الحروف كاملة لتكوين كلمات صحيحة.", categories:["Word","Puzzle","Educational","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"word-ladder", to:"/games/word-ladder", image:wordImg, title:"Word Ladder", titleAr:"سلم الكلمات", description:"Transform one word into another by changing exactly one letter per step.", descriptionAr:"حوّل كلمة إلى أخرى بتغيير حرف واحد فقط في كل خطوة.", categories:["Word","Logic","Educational","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"spelling-master", to:"/games/spelling-master", image:wordImg, title:"Spelling Master", titleAr:"خبير التهجئة", description:"Listen to clear word prompts and enter accurate spellings.", descriptionAr:"استمع إلى الكلمات بوضوح ثم اكتب تهجئتها الصحيحة.", categories:["Word","Audio","Educational","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Audio"], accessible:true }),
  game({ slug:"restaurant-manager", to:"/games/restaurant-manager", image:starchefImg, title:"Restaurant Manager", titleAr:"مدير المطعم", description:"Balance menu quality, staff wellbeing, seating, and operating cash.", descriptionAr:"وازن جودة القائمة وراحة الموظفين والمقاعد والسيولة التشغيلية.", categories:["Business Simulation","Simulation","Cooking","Strategy","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"farm-manager", to:"/games/farm-manager", image:tradetycoonImg, title:"Farm Manager", titleAr:"مدير المزرعة", description:"Manage soil, workers, irrigation, yield, and seasonal sales.", descriptionAr:"أدر التربة والعمال والري والمحصول والمبيعات الموسمية.", categories:["Business Simulation","Simulation","Strategy","Educational","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"city-builder", to:"/games/city-builder", image:dreamhomeImg, title:"City Builder", titleAr:"بناء المدينة", description:"Develop housing, transit, parks, capacity, and public trust.", descriptionAr:"طوّر الإسكان والنقل والحدائق والقدرة الاستيعابية وثقة السكان.", categories:["City Builder","Simulation","Strategy","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"delivery-simulator", to:"/games/delivery-simulator", image:velocityImg, title:"Delivery Simulator", titleAr:"محاكي التوصيل", description:"Optimize routes, drivers, vehicles, contracts, and delivery quality.", descriptionAr:"حسّن المسارات والسائقين والمركبات والعقود وجودة التوصيل.", categories:["Business Simulation","Simulation","Strategy","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"snake", to:"/games/snake", image:neonbreachImg, title:"Snake", titleAr:"الثعبان", description:"Guide a growing snake through a responsive twelve-by-twelve arena.", descriptionAr:"وجّه ثعباناً متنامياً داخل ساحة متجاوبة 12×12.", categories:["Classic","Arcade","Action","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Arrow keys","Touch"], accessible:true }),
  game({ slug:"block-stacker", to:"/games/block-stacker", image:logiquestImg, title:"Block Stacker", titleAr:"ترتيب الكتل", description:"Place compact pieces, complete rows, and prevent the grid from filling.", descriptionAr:"ضع القطع وأكمل الصفوف وامنع امتلاء الشبكة.", categories:["Classic","Arcade","Puzzle","Logic","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"breakout", to:"/games/breakout", image:neonbreachImg, title:"Breakout", titleAr:"تحطيم الطوب", description:"Direct paddle returns across eight columns to clear every brick.", descriptionAr:"وجّه ارتدادات المضرب عبر ثمانية أعمدة لتحطيم جميع قطع الطوب.", categories:["Classic","Arcade","Action","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"bubble-shooter", to:"/games/bubble-shooter", image:reactionTestImg, title:"Bubble Shooter", titleAr:"قاذف الفقاعات", description:"Identify and clear connected color groups of three or more bubbles.", descriptionAr:"حدد مجموعات الألوان المتصلة وامسح ثلاث فقاعات أو أكثر.", categories:["Arcade","Puzzle","Kids","Accessible"], difficulty:"Easy", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"technology-quiz", to:"/games/technology-quiz", image:quizImg, title:"Technology Quiz", titleAr:"اختبار التقنية", description:"Test practical knowledge of computing, security, storage, and the web.", descriptionAr:"اختبر معلوماتك العملية بالحوسبة والأمان والتخزين والويب.", categories:["Quiz","Educational","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"nature-quiz", to:"/games/nature-quiz", image:quizImg, title:"Nature Quiz", titleAr:"اختبار الطبيعة", description:"Explore ecosystems, plants, animals, and essential natural processes.", descriptionAr:"استكشف النظم البيئية والنباتات والحيوانات والعمليات الطبيعية.", categories:["Quiz","Educational","Kids","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"space-quiz", to:"/games/space-quiz", image:quizImg, title:"Space Quiz", titleAr:"اختبار الفضاء", description:"Challenge your knowledge of planets, galaxies, moons, and distance.", descriptionAr:"اختبر معرفتك بالكواكب والمجرات والأقمار والمسافات الفضائية.", categories:["Quiz","Educational","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"sports-quiz", to:"/games/sports-quiz", image:quizImg, title:"Sports Quiz", titleAr:"اختبار الرياضة", description:"Answer focused questions across football, basketball, swimming, and racket sports.", descriptionAr:"أجب عن أسئلة في كرة القدم والسلة والسباحة ورياضات المضرب.", categories:["Quiz","Sports","Educational","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"audio-memory", to:"/games/audio-memory", image:earmasterImg, title:"Audio Memory", titleAr:"الذاكرة الصوتية", description:"Listen and reproduce progressively longer high and low cue sequences.", descriptionAr:"استمع وكرر تسلسلات صوتية عالية ومنخفضة تزداد طولاً.", categories:["Audio","Memory","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Audio","Touch"], accessible:true }),
  game({ slug:"sound-hunt", to:"/games/sound-hunt", image:blindMazeImg, title:"Sound Hunt", titleAr:"البحث الصوتي", description:"Locate announced near, far, left, and right audio clues.", descriptionAr:"حدد الإشارات الصوتية القريبة والبعيدة واليسرى واليمنى.", categories:["Audio","Accessible","Adventure"], difficulty:"Easy", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Audio","Touch"], accessible:true }),
  game({ slug:"echo-locator", to:"/games/echo-locator", image:blindMazeImg, title:"Echo Locator", titleAr:"محدد الصدى", description:"Estimate obstacle distance from measured echo delays.", descriptionAr:"قدّر مسافة العوائق اعتماداً على زمن تأخر الصدى.", categories:["Audio","Physics","Educational","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Audio","Touch"], accessible:true }),
  game({ slug:"rhythm-navigation", to:"/games/rhythm-navigation", image:earmasterImg, title:"Rhythm Navigation", titleAr:"التنقل الإيقاعي", description:"Listen to a timed rhythm and reproduce four beats within tolerance.", descriptionAr:"استمع إلى إيقاع زمني وكرر أربع نبضات ضمن هامش الدقة.", categories:["Audio","Music","Reaction","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Audio","Touch"], accessible:true }),
  game({ slug:"balance-lab", to:"/games/balance-lab", image:logiquestImg, title:"Balance Lab", titleAr:"مختبر التوازن", description:"Balance lever torque through mass and distance experiments.", descriptionAr:"وازن عزم الرافعة عبر تجارب الكتلة والمسافة.", categories:["Physics","Educational","Logic","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"pendulum-puzzle", to:"/games/pendulum-puzzle", image:logiquestImg, title:"Pendulum Puzzle", titleAr:"لغز البندول", description:"Estimate oscillation periods as pendulum length changes.", descriptionAr:"قدّر زمن الاهتزاز مع تغير طول البندول.", categories:["Physics","Educational","Puzzle","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"trajectory-master", to:"/games/trajectory-master", image:tacticalImg, title:"Trajectory Master", titleAr:"خبير المسار", description:"Calibrate launch speed and angle to reach measured target distances.", descriptionAr:"اضبط سرعة وزاوية الإطلاق للوصول إلى مسافات محددة.", categories:["Physics","Educational","Strategy","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"magnet-lab", to:"/games/magnet-lab", image:laptoptechImg, title:"Magnet Lab", titleAr:"مختبر المغناطيس", description:"Predict attraction, repulsion, and force across magnetic experiments.", descriptionAr:"تنبأ بالتجاذب والتنافر والقوة عبر تجارب مغناطيسية.", categories:["Physics","Educational","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"penalty-shootout", to:"/games/penalty-shootout", image:penaltyShootoutImg, title:"Penalty Shootout", titleAr:"ركلات الجزاء", description:"Place controlled penalty shots away from an adapting goalkeeper.", descriptionAr:"سدّد ركلات جزاء متحكم بها بعيداً عن حارس مرمى متكيّف.", categories:["Sports","Reaction","Arcade","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"basketball-challenge", to:"/games/basketball-challenge", image:basketballChallengeImg, title:"Basketball Challenge", titleAr:"تحدي كرة السلة", description:"Calibrate power and aim across progressively longer basketball shots.", descriptionAr:"اضبط القوة والتصويب عبر رميات سلة تتدرج في المسافة.", categories:["Sports","Physics","Arcade","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"table-tennis", to:"/games/table-tennis", image:tableTennisImg, title:"Table Tennis", titleAr:"تنس الطاولة", description:"Read opponent position and return the ball into open court.", descriptionAr:"اقرأ موقع الخصم وأعد الكرة إلى المساحة المفتوحة.", categories:["Sports","Reaction","Strategy","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"air-hockey", to:"/games/air-hockey", image:airHockeyImg, title:"Air Hockey", titleAr:"الهوكي الهوائي", description:"Select shooting lanes and controlled power to beat the defense.", descriptionAr:"اختر مسارات التسديد والقوة المناسبة لتجاوز الدفاع.", categories:["Sports","Arcade","Reaction","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"rhythm-keys", to:"/games/rhythm-keys", image:earmasterImg, title:"Rhythm Keys", titleAr:"مفاتيح الإيقاع", description:"Hear and reproduce increasingly varied four-beat timing patterns.", descriptionAr:"استمع وأعد أنماطاً زمنية متنوعة من أربع نبضات.", categories:["Music","Audio","Reaction","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Audio","Touch"], accessible:true }),
  game({ slug:"melody-memory", to:"/games/melody-memory", image:earmasterImg, title:"Melody Memory", titleAr:"ذاكرة الألحان", description:"Memorize and replay note sequences that grow every round.", descriptionAr:"احفظ تسلسلات النغمات وأعد عزفها بينما تزداد في كل جولة.", categories:["Music","Audio","Memory","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Audio","Touch"], accessible:true }),
  game({ slug:"beat-matcher", to:"/games/beat-matcher", image:earmasterImg, title:"Beat Matcher", titleAr:"مطابقة النبض", description:"Maintain a steady 120 BPM pulse across a measured eight-beat session.", descriptionAr:"حافظ على نبض ثابت بسرعة 120 ضربة خلال جلسة من ثماني نبضات.", categories:["Music","Reaction","Audio","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"piano-trainer", to:"/games/piano-trainer", image:earmasterImg, title:"Piano Trainer", titleAr:"مدرب البيانو", description:"Practice maintained note lessons on an accessible one-octave keyboard.", descriptionAr:"تدرّب على دروس نغمية منظمة باستخدام لوحة موسيقية متاحة من أوكتاف واحد.", categories:["Music","Educational","Audio","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Audio","Touch"], accessible:true }),
  game({ slug:"symmetry-sketch", to:"/games/symmetry-sketch", image:fashionImg, title:"Symmetry Sketch", titleAr:"رسم التناظر", description:"Create balanced artwork on a keyboard-operable mirrored drawing grid.", descriptionAr:"أنشئ رسومات متوازنة على شبكة رسم متناظرة قابلة للتحكم بلوحة المفاتيح.", categories:["Drawing","Educational","Puzzle","Accessible"], difficulty:"Easy", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"pixel-canvas", to:"/games/pixel-canvas", image:fashionImg, title:"Pixel Canvas", titleAr:"لوحة البكسل", description:"Compose multi-color pixel artwork through a semantic six-by-six canvas.", descriptionAr:"صمّم لوحة بكسل متعددة الألوان عبر شبكة دلالية من ستة في ستة.", categories:["Drawing","Kids","Accessible"], difficulty:"Easy", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"shape-designer", to:"/games/shape-designer", image:dreamhomeImg, title:"Shape Designer", titleAr:"مصمم الأشكال", description:"Construct solid geometric forms and validate their measured bounds.", descriptionAr:"ابنِ أشكالاً هندسية مصمتة وتحقق من أبعادها المقاسة.", categories:["Drawing","Educational","Logic","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"pattern-artist", to:"/games/pattern-artist", image:memoryImg, title:"Pattern Artist", titleAr:"فنان الأنماط", description:"Reproduce structured color patterns with measured cell-level accuracy.", descriptionAr:"أعد إنتاج أنماط لونية منظمة مع قياس الدقة على مستوى الخلايا.", categories:["Drawing","Memory","Puzzle","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"lemonade-stand", to:"/games/lemonade-stand", image:starchefImg, title:"Lemonade Stand", titleAr:"كشك الليمونادة", description:"Balance supplies, service capacity, quality, cash, and customer trust.", descriptionAr:"وازن الإمدادات وطاقة الخدمة والجودة والسيولة وثقة العملاء.", categories:["Business Simulation","Cooking","Strategy","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"space-miner-idle", to:"/games/space-miner-idle", image:neonbreachImg, title:"Space Miner Idle", titleAr:"عامل منجم الفضاء", description:"Develop orbital mining capacity through measured resource cycles.", descriptionAr:"طوّر قدرة التعدين المداري عبر دورات موارد محسوبة.", categories:["Idle","Simulation","Strategy","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"factory-idle", to:"/games/factory-idle", image:laptoptechImg, title:"Factory Idle", titleAr:"المصنع التلقائي", description:"Manage materials, production lines, quality control, and buyer reputation.", descriptionAr:"أدر المواد وخطوط الإنتاج وضبط الجودة وسمعة المشترين.", categories:["Idle","Business Simulation","Strategy","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"aquarium-keeper", to:"/games/aquarium-keeper", image:memoryImg, title:"Aquarium Keeper", titleAr:"حارس الأكواريوم", description:"Maintain habitat capacity, water quality, supplies, and visitor trust.", descriptionAr:"حافظ على سعة الموائل وجودة المياه والإمدادات وثقة الزوار.", categories:["Simulation","Kids","Educational","Accessible"], difficulty:"Easy", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"garden-planner", to:"/games/garden-planner", image:dreamhomeImg, title:"Garden Planner", titleAr:"مخطط الحديقة", description:"Plan seed supply, garden beds, plant health, and community reputation.", descriptionAr:"خطط للبذور وأحواض الزراعة وصحة النباتات وسمعة المجتمع.", categories:["Simulation","Educational","Strategy","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"museum-curator", to:"/games/museum-curator", image:tradetycoonImg, title:"Museum Curator", titleAr:"أمين المتحف", description:"Acquire exhibits, expand galleries, improve curation, and earn public trust.", descriptionAr:"اقتَنِ المعروضات ووسّع الصالات وحسّن التنسيق واكسب ثقة الجمهور.", categories:["Business Simulation","Educational","Strategy","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"wildlife-rescue", to:"/games/wildlife-rescue", image:jungleImg, title:"Wildlife Rescue", titleAr:"إنقاذ الحياة البرية", description:"Coordinate supplies, rescue teams, treatment quality, and public confidence.", descriptionAr:"نسّق الإمدادات وفرق الإنقاذ وجودة العلاج وثقة المجتمع.", categories:["Simulation","Strategy","Educational","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"solitaire", to:"/games/solitaire", image:card99Img, title:"Solitaire", titleAr:"سوليتير", description:"Build descending alternating-color card sequences and clear the tableau.", descriptionAr:"ابنِ تسلسلات بطاقات تنازلية متعاقبة الألوان وأخلِ الطاولة.", categories:["Card","Classic","Strategy","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"spider-solitaire", to:"/games/spider-solitaire", image:briscolaImg, title:"Spider Solitaire", titleAr:"سبايدر سوليتير", description:"Organize same-suit descending runs under focused Spider rules.", descriptionAr:"نظّم تسلسلات تنازلية من النوع نفسه وفق قواعد سبايدر المركزة.", categories:["Card","Classic","Strategy","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"freecell", to:"/games/freecell", image:farkleImg, title:"FreeCell", titleAr:"فري سيل", description:"Plan exposed-card moves across open columns with FreeCell sequencing.", descriptionAr:"خطط لتحريك البطاقات المكشوفة عبر الأعمدة المفتوحة وفق تسلسل فري سيل.", categories:["Card","Classic","Logic","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"mahjong", to:"/games/mahjong", image:dominoesImg, title:"Mahjong", titleAr:"ماجونغ", description:"Remove matching free-edge tiles from a semantic compact layout.", descriptionAr:"أزل أزواج البلاطات المتطابقة ذات الجانب الحر من تخطيط دلالي مدمج.", categories:["Classic","Puzzle","Board","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"tower-defense", to:"/games/tower-defense", image:tacticalImg, title:"Tower Defense", titleAr:"الدفاع بالأبراج", description:"Place measured-range towers and defend four escalating path waves.", descriptionAr:"ضع أبراجاً بمدى محسوب ودافع عن المسار خلال أربع موجات متصاعدة.", categories:["Tower Defense","Strategy","Arcade","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"maze-runner", to:"/games/maze-runner", image:blindMazeImg, title:"Maze Runner", titleAr:"عداء المتاهة", description:"Navigate a coordinate-labelled maze through walls to the goal.", descriptionAr:"تنقل عبر متاهة معنونة بالإحداثيات متجاوزاً الجدران نحو الهدف.", categories:["Adventure","Puzzle","Logic","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"parking-challenge", to:"/games/parking-challenge", image:velocityImg, title:"Parking Challenge", titleAr:"تحدي ركن السيارة", description:"Route a vehicle around obstacles into a precisely marked parking bay.", descriptionAr:"وجّه المركبة حول العوائق إلى موقف محدد بدقة.", categories:["Simulation","Puzzle","Logic","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"escape-room", to:"/games/escape-room", image:logiquestImg, title:"Escape Room", titleAr:"غرفة الهروب", description:"Solve three maintained word clues to unlock the final exit.", descriptionAr:"حل ثلاثة ألغاز لفظية منظمة لفتح المخرج النهائي.", categories:["Adventure","Puzzle","Word","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"chess", to:"/games/chess", image:chessImg, title:"Chess", titleAr:"شطرنج", description:"Play full-rules chess against a calculating engine across three depths.", descriptionAr:"العب شطرنجاً بقواعده الكاملة ضد محرك يحسب حركاته على ثلاثة مستويات.", categories:["Board","Classic","Strategy","Logic","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, featured:true, recentlyAdded:true, controls:["Keyboard","Touch","Pointer"], accessible:true }),
  game({ slug:"backgammon", to:"/games/backgammon", image:backgammonImg, title:"Backgammon", titleAr:"طاولة الزهر", description:"Bear off all fifteen checkers, using the bar, hits, and exact rolls.", descriptionAr:"أخرج أحجارك الخمسة عشر مستخدماً البار والضرب والرميات المضبوطة.", categories:["Board","Classic","Strategy","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, featured:true, recentlyAdded:true, controls:["Keyboard","Touch","Pointer"], accessible:true }),
  game({ slug:"ludo", to:"/games/ludo", image:ludoImg, title:"Ludo", titleAr:"لودو", description:"Race three rivals around the cross board and bring four tokens home.", descriptionAr:"سابق ثلاثة منافسين حول رقعة الصليب وأوصل أحجارك الأربعة إلى المركز.", categories:["Board","Classic","Strategy","Kids","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch","Pointer"], accessible:true }),
  game({ slug:"word-master", to:"/games/word-master", image:wordMasterImg, title:"Word Master", titleAr:"سيد الكلمات", description:"Guess the five-letter word in six tries, in Arabic or English.", descriptionAr:"خمّن كلمة الخمسة حروف خلال ست محاولات بالعربية أو الإنجليزية.", categories:["Word","Puzzle","Educational","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, trending:true, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"skybound-quest", to:"/games/skybound-quest", image:skyboundImg, title:"Skybound Quest", titleAr:"مغامرة بوابة السماء", description:"Jump between sky platforms for every gem, one unhurried move at a time.", descriptionAr:"اقفز بين منصات السماء لجمع كل جوهرة، بحركة واحدة كاملة في كل مرة.", categories:["Platform","Adventure","Puzzle","Logic","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, trending:true, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"hex", to:"/games/hex", image:logiquestImg, title:"Hex", titleAr:"هيكس", description:"Build an unbroken edge-to-edge path across a compact tactical board.", descriptionAr:"ابنِ مساراً متصلاً من حافة إلى أخرى على لوحة تكتيكية مدمجة.", categories:["Board","Strategy","Logic","Accessible"], difficulty:"Hard", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"mancala", to:"/games/mancala", image:dominoesImg, title:"Mancala", titleAr:"منقلة", description:"Sow stones, earn extra turns, and capture the opposite pits strategically.", descriptionAr:"وزّع الأحجار واكسب أدواراً إضافية والتقط الحفر المقابلة باستراتيجية.", categories:["Board","Classic","Strategy","Math","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
  game({ slug:"royal-game-of-ur", to:"/games/royal-game-of-ur", image:visionopolyImg, title:"Royal Game of Ur", titleAr:"لعبة أور الملكية", description:"Guide three pieces through an exact-roll race inspired by the ancient board game.", descriptionAr:"وجّه ثلاث قطع في سباق يعتمد الرمية الدقيقة مستوحى من اللعبة الأثرية القديمة.", categories:["Board","Classic","Strategy","Educational","Accessible"], difficulty:"Medium", age:"Everyone", players:"1", plays:0, rating:0, recentlyAdded:true, controls:["Keyboard","Touch"], accessible:true }),
];

export function getArcadeGame(pathname: string) {
  return ARCADE_GAMES.find((item) => item.to === pathname);
}

export function localizeGame(item: ArcadeGame, lang: string) {
  return lang === "ar"
    ? { title: item.titleAr, description: item.descriptionAr }
    : { title: item.title, description: item.description };
}
