import { BarChart3, BookOpen, Clock3, ShieldCheck, Sparkles, Star } from "lucide-react";
import { useChildProgress } from "./useChildProgress";

export function ParentDashboard({ ar }: { ar:boolean }) {
  const progress = useChildProgress();
  return <section aria-labelledby="parent-dashboard-title" className="rounded-3xl border border-sky-200 bg-white p-6 text-slate-900 shadow-xl sm:p-8">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold text-violet-700">{ar ? "خاص بالوالدين" : "For parents"}</p><h2 id="parent-dashboard-title" className="text-2xl font-black">{ar ? "لوحة تقدم الطفل" : "Child progress dashboard"}</h2></div><span className="flex items-center gap-2 text-xs text-emerald-800"><ShieldCheck className="h-4 w-4" />{ar ? "البيانات محفوظة على هذا الجهاز" : "Data stays on this device"}</span></div>
    <dl className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Clock3} label={ar ? "وقت اللعب" : "Play time"} value={`${Math.round(progress.totalSeconds / 60)} min`} /><Metric icon={BookOpen} label={ar ? "ألعاب مكتملة" : "Games completed"} value={String(progress.completedGames)} /><Metric icon={Star} label={ar ? "النجوم" : "Stars"} value={String(progress.stars)} /><Metric icon={BarChart3} label={ar ? "المستوى" : "Level"} value={String(progress.level)} /></dl>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><div><h3 className="font-bold">{ar ? "المهارات المكتسبة" : "Skills earned"}</h3><div className="mt-3 flex flex-wrap gap-2">{progress.earnedSkills.length ? progress.earnedSkills.map((skill) => <span key={skill} className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-900">{skill}</span>) : <p className="text-sm text-slate-500">{ar ? "ستظهر المهارات بعد إكمال الألعاب." : "Skills appear after completed games."}</p>}</div></div><div><h3 className="font-bold">{ar ? "النشاط الأخير" : "Recent activity"}</h3><ul className="mt-3 space-y-2">{progress.records.filter((item) => item.data.playCount).slice(0,4).map((item) => <li key={item.game.slug} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2 text-sm"><span>{item.game.title}</span><span className="text-slate-500">{item.data.playCount} plays</span></li>)}{!progress.records.some((item) => item.data.playCount) && <li className="text-sm text-slate-500">{ar ? "لا يوجد نشاط بعد." : "No activity yet."}</li>}</ul></div></div>
    <p className="mt-6 flex items-start gap-2 border-t pt-4 text-xs leading-5 text-slate-500"><Sparkles className="mt-0.5 h-4 w-4 shrink-0" />{ar ? "النجوم والشارات تعليمية داخلية. لا تُمنح مكافآت VX للأطفال إلا وفق سياسة المنصة وبعد موافقة واضحة." : "Stars and badges are internal learning rewards. VX rewards are not issued to children without platform policy and explicit approval."}</p>
  </section>;
}

function Metric({ icon:Icon, label, value }: { icon:typeof Clock3; label:string; value:string }) { return <div className="rounded-2xl bg-gradient-to-br from-sky-50 to-violet-50 p-4"><dt className="flex items-center gap-2 text-xs font-semibold text-slate-600"><Icon className="h-4 w-4 text-violet-600" />{label}</dt><dd className="mt-2 text-2xl font-black">{value}</dd></div>; }
