// The semantic index the assistants and the content engine read from.
//
// Moved out of embed-content so the daily content run can fill a section that
// has never been indexed, with exactly the same rules the admin button uses:
// only published, active rows, and never anything that identifies a child.

import { createEmbedding } from "./aiProvider.ts";
import servicesCatalog from "./data/servicesCatalog.json" with { type: "json" };

// deno-lint-ignore no-explicit-any
type ServiceClient = any;

/**
 * Services are a code catalogue, not a table — the approved Phase 1 decision
 * was to index it rather than duplicate it into the database. This snapshot is
 * generated by `npx vite-node scripts/generate-services-index.ts` and kept in
 * step by src/test/services-index.test.ts.
 *
 * It is indexed into the same `ai_embeddings` table under the virtual source
 * name `services`, so retrieval stays one system.
 */
export const SERVICES_SOURCE = "services";

interface IndexedService {
  id: string;
  text: string;
}

// Which tables get embedded and how their searchable text is built.
//
// Phase 1 widened this from two tables to the user-facing domains the AI Core
// is expected to know about. Three deliberate exclusions:
//
//  - `library_books` already carries its own `embedding` column and is served
//    by library-semantic-search / library-embed-book. Indexing it here too
//    would be a second semantic system for the same rows, which the spec
//    forbids. Cross-domain queries reach the library through that index.
//  - Anything under `kids_*` that identifies a child. Only the public
//    catalogue of games is indexed, never progress, messages or profiles.
//  - Tables with no user-facing text worth retrieving.
//
// `filter` keeps unpublished and inactive rows out of the index, so the AI
// cannot recommend something a visitor cannot reach.
interface SourceConfig {
  columns: string;
  toText: (r: Record<string, unknown>) => string;
  /** Applied as .eq() pairs; keeps drafts and disabled rows unindexed. */
  filter?: Record<string, unknown>;
}

export const SOURCES: Record<string, SourceConfig> = {
  products: {
    columns: "id, name, description, category, store_type",
    toText: (r) => [r.name, r.category, r.store_type, r.description].filter(Boolean).join(". "),
  },
  content_items: {
    columns: "id, title, description, category, type, level",
    toText: (r) => [r.title, r.category, r.type, r.level, r.description].filter(Boolean).join(". "),
    filter: { published: true },
  },
  academy_courses: {
    columns: "id, title, description, subject, category, level, difficulty, tags, learning_outcomes",
    toText: (r) =>
      [r.title, r.subject, r.category, r.level, r.difficulty, r.description,
       Array.isArray(r.tags) ? (r.tags as string[]).join(", ") : null,
       Array.isArray(r.learning_outcomes) ? (r.learning_outcomes as string[]).join(". ") : null]
        .filter(Boolean).join(". "),
    filter: { published: true },
  },
  kids_games: {
    columns: "id, title, description, difficulty, age_range, tags, accessibility_features, status",
    toText: (r) =>
      [r.title, r.description, r.difficulty, r.age_range,
       Array.isArray(r.tags) ? (r.tags as string[]).join(", ") : null,
       Array.isArray(r.accessibility_features) ? (r.accessibility_features as string[]).join(", ") : null]
        .filter(Boolean).join(". "),
    filter: { status: "published" },
  },
  simulations: {
    columns: "id, title, description, difficulty, subcategory",
    toText: (r) => [r.title, r.subcategory, r.difficulty, r.description].filter(Boolean).join(". "),
    filter: { published: true },
  },
  tv_channels: {
    columns: "id, name, name_ar, description, description_ar, country, language",
    toText: (r) => [r.name, r.name_ar, r.country, r.language, r.description, r.description_ar].filter(Boolean).join(". "),
    filter: { is_active: true },
  },
  radio_stations: {
    columns: "id, name, name_ar, description, description_ar, country, language",
    toText: (r) => [r.name, r.name_ar, r.country, r.language, r.description, r.description_ar].filter(Boolean).join(". "),
    filter: { is_active: true },
  },
  communities: {
    columns: "id, name, description, category",
    toText: (r) => [r.name, r.category, r.description].filter(Boolean).join(". "),
  },
  events: {
    columns: "id, title, description, event_type, location",
    toText: (r) => [r.title, r.event_type, r.location, r.description].filter(Boolean).join(". "),
  },
  jobs: {
    columns: "id, title, description, job_type, location, experience_level, skills_required, accessibility_friendly",
    toText: (r) =>
      [r.title, r.job_type, r.location, r.experience_level,
       Array.isArray(r.skills_required) ? (r.skills_required as string[]).join(", ") : null,
       r.accessibility_friendly ? "accessibility friendly" : null, r.description]
        .filter(Boolean).join(". "),
    filter: { status: "open" },
  },
};


const BATCH = 50;

/**
 * The id a catalogue service is stored under.
 *
 * `ai_embeddings.source_id` is a uuid and catalogue ids are slugs
 * ("egg-incubator"), so every services upsert used to fail and the catalogue
 * was never searchable. A slug is turned into a stable name-based uuid
 * (SHA-256, version 5 layout) instead; the slug itself travels in `content`.
 */
export async function serviceSourceId(slug: string): Promise<string> {
  const digest = new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(`visionex:services:${slug}`)));
  const bytes = digest.slice(0, 16);
  bytes[6] = (bytes[6] & 0x0f) | 0x50;
  bytes[8] = (bytes[8] & 0x3f) | 0x80;
  const hex = Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

/** Catalogue services by their stored id, for turning a match back into a service. */
let servicesByStoredId: Promise<Map<string, IndexedService>> | null = null;
export function catalogServicesByStoredId(): Promise<Map<string, IndexedService>> {
  servicesByStoredId ??= Promise.all(
    (servicesCatalog as IndexedService[]).map(async (s) => [await serviceSourceId(s.id), s] as const),
  ).then((pairs) => new Map(pairs));
  return servicesByStoredId;
}

/** Every source name the index knows. */
export const INDEX_SOURCES: string[] = [...Object.keys(SOURCES), SERVICES_SOURCE];

/**
 * (Re)build the index for the given sources. Returns how many rows each got;
 * -1 for a table that could not be read.
 */
export async function indexSources(
  service: ServiceClient,
  requested: string[],
  options: { limit?: number } = {},
): Promise<Record<string, number>> {
  const tables = requested.filter((t) => t !== SERVICES_SOURCE && SOURCES[t]);
  const indexServices = requested.includes(SERVICES_SOURCE);
  const limit = Math.min(Math.max(options.limit ?? 2000, 1), 2000);

  const summary: Record<string, number> = {};

  for (const table of tables) {
    const cfg = SOURCES[table];
    let query = service.from(table).select(cfg.columns).limit(limit);
    for (const [column, value] of Object.entries(cfg.filter ?? {})) {
      query = query.eq(column, value);
    }
    const { data: rows, error } = await query;
    // One table failing — a column renamed, a table not yet deployed — must
    // not abandon the tables that would have indexed fine.
    if (error) {
      console.error(`[embed-content] skipping ${table}:`, error.message);
      summary[table] = -1;
      continue;
    }
    if (!rows || rows.length === 0) { summary[table] = 0; continue; }

    let embedded = 0;
    for (let i = 0; i < rows.length; i += BATCH) {
      const chunk = rows.slice(i, i + BATCH) as Array<Record<string, unknown>>;
      const texts = chunk.map((r) => cfg.toText(r).slice(0, 6000));
      const vectors = await createEmbedding(texts);

      const upserts = chunk.map((r, j) => ({
        source_table: table,
        source_id: r.id,
        content: texts[j],
        embedding: vectors[j],
        updated_at: new Date().toISOString(),
      }));
      const { error: upErr } = await service
        .from("ai_embeddings")
        .upsert(upserts, { onConflict: "source_table,source_id" });
      if (upErr) throw upErr;
      embedded += upserts.length;
    }
    summary[table] = embedded;
  }

  // Services come from the committed catalogue snapshot rather than a table,
  // but land in the same ai_embeddings store under the `services` source, so
  // one semantic search covers them alongside everything else.
  if (indexServices) {
    const services = servicesCatalog as IndexedService[];
    let embedded = 0;
    for (let i = 0; i < services.length; i += BATCH) {
      const chunk = services.slice(i, i + BATCH);
      const vectors = await createEmbedding(chunk.map((s) => s.text.slice(0, 6000)));
      const ids = await Promise.all(chunk.map((s) => serviceSourceId(s.id)));
      const { error: upErr } = await service.from("ai_embeddings").upsert(
        chunk.map((s, j) => ({
          source_table: SERVICES_SOURCE,
          source_id: ids[j],
          content: s.text,
          embedding: vectors[j],
          updated_at: new Date().toISOString(),
        })),
        { onConflict: "source_table,source_id" },
      );
      if (upErr) throw upErr;
      embedded += chunk.length;
    }
    summary[SERVICES_SOURCE] = embedded;
  }

  return summary;
}
