import { Layout } from "@/components/Layout";
import { TriangleAlert } from "lucide-react";

const clauses = [
  {
    title: "General Purpose",
    body: "Visionex is a digital platform offering educational tools, interactive simulations, games, VXBazaar marketplace services, community features, AI-powered assistants, voice communication, and a virtual currency system (VX Coins). All platform features are provided for informational, educational, and entertainment purposes only.",
  },
  {
    title: "Not Professional Advice",
    body: "Nothing on Visionex — including content generated by AI assistants, nutrition analysis tools, career guidance features, business simulation results, or community posts — constitutes professional, legal, medical, financial, or investment advice. Always consult a qualified professional before making decisions based on information obtained from this platform.",
  },
  {
    title: "AI-Generated Content",
    body: "Visionex integrates AI features powered by OpenAI. AI responses are generated automatically and may be inaccurate, outdated, incomplete, or misleading. Visionex does not review or verify AI-generated outputs before they are displayed. You should independently verify any important information obtained from AI features. Do not rely on AI responses for medical diagnoses, legal decisions, financial transactions, or safety-critical matters.",
  },
  {
    title: "VXBazaar Marketplace",
    body: "Visionex operates VXBazaar as a technology platform connecting independent buyers and sellers. Visionex is not a party to any transaction between users. We do not verify the accuracy, legality, or quality of products or services listed by sellers. Buyers transact at their own risk. Visionex disclaims all liability for disputes, losses, or damages arising from marketplace transactions.",
  },
  {
    title: "VX Coins & Virtual Currency",
    body: "VX Coins are a platform-only virtual reward currency with no real-world monetary value. They cannot be exchanged for cash, redeemed externally, or transferred to other platforms. Visionex reserves the right to adjust, reset, or terminate the VX Coins system at any time without compensation. Loss of VX Coins due to account termination for violations of our Terms of Use is not subject to appeal.",
  },
  {
    title: "User-Generated Content",
    body: "Visionex hosts content created by its users including posts, product listings, shop descriptions, community discussions, and messages. Visionex does not endorse, verify, or guarantee the accuracy, legality, or quality of user-generated content. Users are solely responsible for the content they submit. Visionex may remove content at its discretion but is not obligated to review all content before it is published.",
  },
  {
    title: "Third-Party Services",
    body: "Visionex integrates third-party services including Supabase, OpenAI, Google AdSense, and LiveKit. Visionex is not responsible for the availability, reliability, accuracy, or practices of these third-party providers. Disruption to a third-party service may affect Visionex features without prior notice. Links or references to external websites are provided for convenience only and do not constitute an endorsement.",
  },
  {
    title: "Accessibility Features",
    body: "While Visionex is committed to providing an accessible experience and continuously improves its accessibility features, we do not guarantee that all platform functionality will be fully accessible on every device, browser, or assistive technology configuration. Users who encounter accessibility barriers are encouraged to contact us so we can address them.",
  },
  {
    title: "Limitation of Liability",
    body: 'Visionex is provided on an "as-is" and "as-available" basis without warranties of any kind. To the fullest extent permitted by applicable law, Visionex, its operators, affiliates, employees, and agents shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages including but not limited to loss of data, loss of revenue, personal injury, or property damage arising from your use of the platform, reliance on platform content, marketplace transactions, AI outputs, or service interruptions. Total liability shall not exceed the amount paid by the user to Visionex in the preceding 12 months.',
  },
  {
    title: "Service Availability",
    body: "Visionex does not guarantee uninterrupted or error-free service. The platform may be modified, suspended, or discontinued at any time with or without notice. Scheduled maintenance, technical issues, or circumstances beyond our control may cause temporary unavailability. Visionex shall not be liable for any losses resulting from service downtime.",
  },
  {
    title: "Governing Law & Jurisdiction",
    body: "This disclaimer and all platform-related disputes shall be governed by applicable digital service laws. Users in different jurisdictions may have additional rights under local consumer protection, data privacy, and digital services laws that this disclaimer does not override. Nothing herein limits rights that cannot be waived under applicable mandatory law.",
  },
  {
    title: "Contact for Legal Matters",
    body: "For legal inquiries, requests related to copyright or intellectual property, or to report legal compliance concerns, please contact us at hello@visionex.app. We aim to respond to formal legal inquiries within 30 business days.",
  },
];

export default function LegalDisclaimer() {
  return (
    <Layout>
      <section className="mx-auto max-w-3xl px-4 py-12">
        <div className="mb-10 flex items-center gap-4">
          <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/10">
            <TriangleAlert className="h-7 w-7 text-primary" />
          </div>
          <div>
            <h1 className="text-3xl font-bold">Legal Disclaimer</h1>
            <p className="mt-1 text-sm text-muted-foreground">Visionex Platform · Last Updated: April 2026</p>
          </div>
        </div>

        <div className="mb-8 rounded-2xl border bg-amber-500/5 border-amber-500/30 p-5">
          <p className="text-sm leading-relaxed text-muted-foreground">
            <strong className="text-amber-600 dark:text-amber-400">Important:</strong> Please read this disclaimer carefully before using Visionex. By accessing or using any part of the platform, you acknowledge and agree to the terms set out below.
          </p>
        </div>

        <div className="space-y-4">
          {clauses.map((clause, i) => (
            <div key={clause.title} className="rounded-2xl border bg-card p-6 shadow-sm">
              <div className="mb-3 flex items-center gap-3">
                <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary/10 text-xs font-bold text-primary">
                  {i + 1}
                </span>
                <h2 className="font-semibold text-foreground">{clause.title}</h2>
              </div>
              <p className="leading-relaxed text-sm text-muted-foreground">{clause.body}</p>
            </div>
          ))}
        </div>

        <div className="mt-10 rounded-2xl border bg-primary/5 p-6 text-center">
          <p className="text-sm text-muted-foreground">
            Legal inquiries may be directed to{" "}
            <a href="mailto:hello@visionex.app" className="font-semibold text-primary underline underline-offset-4">
              hello@visionex.app
            </a>
          </p>
        </div>
      </section>
    </Layout>
  );
}
