import { Accessibility, AudioLines, Compass, Headphones, Keyboard, ShieldCheck, Trophy } from "lucide-react";
import { Layout } from "@/components/Layout";
import { Badge } from "@/components/ui/badge";
import { useLanguage } from "@/contexts/LanguageContext";
import { ArcadeGameCard } from "@/features/arcade/ArcadeGameCard";
import { ARCADE_GAMES } from "@/features/arcade/catalog";
import { ACCESSIBLE_GAME_PRODUCTION_PLAN } from "@/features/arcade/accessible/accessibleGamePlan";

export default function AccessibleGames() {
  const { lang } = useLanguage(); const ar = lang === "ar";
  const available = ARCADE_GAMES.filter((game) => game.accessible);
  return <Layout><div className="min-h-screen bg-[#050914] text-white"><header className="relative overflow-hidden border-b border-cyan-300/15 bg-[radial-gradient(circle_at_80%_10%,rgba(34,211,238,.2),transparent_35%),radial-gradient(circle_at_15%_40%,rgba(139,92,246,.22),transparent_38%)]"><div className="section-container py-20"><Badge className="border border-cyan-200/25 bg-cyan-400/10 text-cyan-100"><Accessibility className="me-2 h-4 w-4" />Visionex Accessible Games</Badge><h1 className="mt-6 max-w-4xl text-5xl font-black tracking-tight sm:text-6xl">{ar ? "اللعب بالصوت، الوصف، والكيبورد" : "Play through sound, description, and keyboard"}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">{ar ? "مركز مصمم من البداية للمكفوفين وضعاف البصر، ويمكن للمبصرين اللعب في التجربة نفسها." : "A center designed from the start for blind and low-vision players, with shared experiences for sighted players too."}</p><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Feature icon={Keyboard} text={ar ? "تحكم بالكيبورد" : "Keyboard control"} /><Feature icon={AudioLines} text={ar ? "وصف الأحداث" : "Event descriptions"} /><Feature icon={Compass} text={ar ? "صوت مكاني جاهز" : "Spatial-ready audio"} /><Feature icon={ShieldCheck} text="WCAG 2.1 AA UI" /></div></div></header>
    <main className="section-container space-y-14 py-12"><section aria-labelledby="available-title"><p className="text-sm font-bold text-cyan-300">{ar ? "متاحة الآن" : "Available now"}</p><h2 id="available-title" className="mt-1 text-3xl font-black">{ar ? "ألعاب بميزات وصول" : "Games with accessibility features"}</h2><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{available.map((game) => <ArcadeGameCard key={game.slug} game={game} lang={lang} />)}</div></section>
      <section aria-labelledby="shortcuts-title" className="rounded-3xl border border-white/10 bg-white/[.05] p-6 sm:p-8"><h2 id="shortcuts-title" className="text-2xl font-black">{ar ? "اختصارات موحدة" : "Shared shortcuts"}</h2><dl className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Shortcut keys="Tab / Shift+Tab" label={ar ? "التنقل" : "Navigate"} /><Shortcut keys="Enter / Space" label={ar ? "تفعيل" : "Activate"} /><Shortcut keys="?" label={ar ? "المساعدة" : "Help"} /><Shortcut keys="S" label={ar ? "حالة قارئ الشاشة" : "Screen-reader status"} /></dl></section>
      <section aria-labelledby="production-title"><p className="text-sm font-bold text-violet-300">{ar ? "خطة الإنتاج الصوتي" : "Audio-first production plan"}</p><h2 id="production-title" className="mt-1 text-3xl font-black">{ar ? "الألعاب الجديدة" : "New accessible games"}</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{ACCESSIBLE_GAME_PRODUCTION_PLAN.map((game) => <article key={game.id} className="rounded-2xl border border-white/10 bg-slate-900 p-5"><div className="flex items-start justify-between gap-3"><div><Headphones className="h-6 w-6 text-cyan-300" /><h3 className="mt-3 text-lg font-black">{game.name}</h3><p className="mt-1 text-sm text-slate-400">{game.mode}</p></div><Badge variant="outline" className={game.status === "development" ? "border-amber-300/40 text-amber-200" : "border-rose-300/40 text-rose-200"}>{game.status}</Badge></div><p className="mt-4 text-xs leading-5 text-slate-400">{ar ? "حاجز الإصدار: " : "Release gate: "}{game.blocker}</p></article>)}</div></section>
      <section className="rounded-3xl border border-amber-300/20 bg-amber-300/10 p-6"><h2 className="flex items-center gap-2 font-black"><Trophy className="h-5 w-5" />{ar ? "التحديات والترتيب" : "Challenges and leaderboard"}</h2><p className="mt-2 text-sm leading-6 text-amber-100">{ar ? "تستخدم الألعاب الحالية نظام النتائج والإنجازات ولوحة الصدارة. التحديات اليومية والمنافسة Blind vs Sighted جاهزة في البنية، لكنها تحتاج أول لعبة صوتية معتمدة واختبار مستخدمين قبل التفعيل." : "Current games use shared scores, achievements, and leaderboard links. Daily challenges and Blind vs Sighted competition are architecture-ready, but require the first approved audio game and user testing before activation."}</p></section>
    </main></div></Layout>;
}

function Feature({ icon:Icon, text }: { icon:typeof Keyboard; text:string }) { return <div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-black/20 p-4"><Icon className="h-5 w-5 text-cyan-300" /><span className="font-semibold">{text}</span></div>; }
function Shortcut({ keys, label }: { keys:string; label:string }) { return <div className="rounded-xl bg-black/25 p-4"><dt><kbd className="rounded bg-white/10 px-2 py-1 font-mono text-xs">{keys}</kbd></dt><dd className="mt-2 text-sm text-slate-300">{label}</dd></div>; }
