import { useState } from "react";
import { CalendarDays, CheckCircle2, Coins, Gift, LockKeyhole, ShoppingBag, Trophy } from "lucide-react";
import { Link, useLocation } from "react-router-dom";
import { Layout } from "@/components/Layout";
import { Button } from "@/components/ui/button";
import { toast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { LOGIN_REWARDS, REWARD_RULES, SHOP_ITEMS, TOURNAMENT_TYPES } from "@/features/arcade/economy/economyCatalog";

type RpcResult = { data: unknown; error: { message: string } | null };
const callArcadeRpc = supabase.rpc as unknown as (name: string, args?: Record<string, unknown>) => Promise<RpcResult>;

export default function ArcadeEconomy() {
  const mode = useLocation().pathname.split("/").pop();
  return <Layout><div className="min-h-screen bg-[#070914] text-white"><header className="border-b border-white/10 bg-[radial-gradient(circle_at_50%_0%,rgba(245,158,11,.2),transparent_45%)]"><div className="section-container py-12"><p className="text-sm font-bold text-amber-300">VISIONEX ARCADE ECONOMY</p><h1 className="mt-2 text-4xl font-black">VX Rewards</h1><p className="mt-3 max-w-2xl text-slate-300">مكافآت تجميلية وعادلة، تُعتمد من الخادم ولا تمنح لمجرد فتح اللعبة.</p><nav aria-label="Arcade economy" className="mt-7 flex flex-wrap gap-2"><Nav to="/games/rewards" label="المكافآت والدخول اليومي" active={mode === "rewards"} /><Nav to="/games/tournaments" label="البطولات" active={mode === "tournaments"} /><Nav to="/games/shop" label="المتجر" active={mode === "shop"} /></nav></div></header><main className="section-container py-10">{mode === "shop" ? <Shop /> : mode === "tournaments" ? <Tournaments /> : <Rewards />}</main></div></Layout>;
}

function Rewards() {
  const [claiming,setClaiming]=useState(false);
  const claim=async()=>{ setClaiming(true); const {data,error}=await callArcadeRpc("arcade_claim_daily_login"); setClaiming(false); if(error){ toast({title:"تعذر استلام المكافأة",description:error.message,variant:"destructive"}); return; } const result=data as {claimed?:boolean;vx?:number;day?:number}; toast({title:result.claimed ? `+${result.vx} VX` : "تم الاستلام اليوم",description:result.claimed ? `مكافأة اليوم ${result.day}` : "عد غداً للحفاظ على السلسلة."}); };
  return <div className="space-y-8"><section className="rounded-3xl border border-amber-300/20 bg-amber-300/[.06] p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="flex items-center gap-2 text-2xl font-black"><Gift className="text-amber-300" />سلسلة الدخول لـ 30 يوماً</h2><p className="mt-2 text-sm text-slate-300">المطالبة مرة واحدة يومياً. الانقطاع يعيد دورة المكافأة إلى اليوم الأول.</p></div><Button onClick={claim} disabled={claiming}>{claiming ? "جارٍ التحقق…" : "استلام مكافأة اليوم"}</Button></div><ol className="mt-6 grid grid-cols-3 gap-2 sm:grid-cols-6 lg:grid-cols-10">{LOGIN_REWARDS.map(item=><li key={item.day} className="rounded-xl border border-white/10 bg-black/20 p-3 text-center"><span className="block text-xs text-slate-400">اليوم {item.day}</span><strong className="mt-1 block text-amber-300">{item.vx} VX</strong></li>)}</ol></section><section><h2 className="text-2xl font-black">قواعد التوزيع</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{REWARD_RULES.map(([event,reward])=><article key={event} className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><CheckCircle2 className="h-5 w-5 text-emerald-300" /><h3 className="mt-3 font-bold">{event}</h3><p className="mt-1 text-amber-300">{reward}</p></article>)}</div><p className="mt-5 flex gap-2 rounded-xl border border-cyan-300/15 bg-cyan-300/5 p-4 text-sm text-slate-300"><LockKeyhole className="h-5 w-5 shrink-0 text-cyan-300" />لا مكافأة للعب المتكرر بلا إنجاز، وكل مطالبة لها مفتاح Idempotency وسجل تدقيق.</p></section></div>;
}

function Shop(){ const [busy,setBusy]=useState<string>(); const buy=async(sku:string)=>{setBusy(sku);const {error}=await callArcadeRpc("arcade_buy_shop_item_by_sku",{_sku:sku,_idempotency_key:crypto.randomUUID()});setBusy(undefined);toast(error?{title:"لم تكتمل العملية",description:error.message,variant:"destructive"}:{title:"تمت الإضافة إلى مجموعتك",description:"العنصر تجميلي ولا يمنح أفضلية داخل اللعبة."});}; return <section><h2 className="flex items-center gap-2 text-3xl font-black"><ShoppingBag className="text-violet-300" />Arcade Shop</h2><p className="mt-2 text-slate-400">الشراء باستخدام VX فقط. كل العناصر تجميلية.</p><div className="mt-6 grid gap-5 md:grid-cols-3">{SHOP_ITEMS.map(item=><article key={item.sku} className="rounded-3xl border border-white/10 bg-white/[.04] p-6"><div className="grid h-20 place-items-center rounded-2xl bg-gradient-to-br from-violet-500/30 to-cyan-400/10"><Coins className="h-9 w-9 text-amber-300" /></div><p className="mt-4 text-xs uppercase text-cyan-300">{item.type}</p><h3 className="mt-1 text-xl font-black">{item.name}</h3><p className="mt-2 min-h-10 text-sm text-slate-400">{item.description}</p><div className="mt-5 flex items-center justify-between"><strong>{item.price} VX</strong><Button onClick={()=>buy(item.sku)} disabled={busy===item.sku}>{busy===item.sku?"جارٍ الشراء…":"شراء"}</Button></div></article>)}</div></section>; }
function Tournaments(){return <section><h2 className="flex items-center gap-2 text-3xl font-black"><Trophy className="text-amber-300" />Tournament Engine</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{TOURNAMENT_TYPES.map(item=><article key={item.period} className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><CalendarDays className="h-6 w-6 text-cyan-300"/><h3 className="mt-3 text-xl font-black">{item.label}</h3><p className="mt-1 text-sm text-slate-400">المدة: {item.duration}</p><ul className="mt-4 space-y-2 text-sm text-slate-300"><li>قوانين وفترة زمنية محددة</li><li>نتائج موثّقة فقط</li><li>لوحة متصدرين وجوائز بعد المراجعة</li></ul></article>)}</div><p className="mt-6 rounded-xl border border-amber-300/15 bg-amber-300/5 p-4 text-sm text-slate-300">تظهر البطولات المنشورة من لوحة الإدارة بعد تطبيق Migration. جوائز البطولة لا تُصرف إلا بعد انتقالها إلى حالة التحقق ثم الاكتمال.</p></section>;}
function Nav({to,label,active}:{to:string;label:string;active:boolean}){return <Link to={to} aria-current={active?"page":undefined} className={`rounded-xl px-4 py-2 text-sm font-bold ${active?"bg-white text-slate-950":"bg-white/5 text-slate-300 hover:bg-white/10"}`}>{label}</Link>;}
