import { Award, CalendarCheck, Clock3, Coins, Gamepad2, Medal, ShieldCheck, ShoppingBag, Trophy, UserRound, Zap } from "lucide-react";
import type { ReactNode } from "react";
import { Link, useLocation } from "react-router-dom";
import { Layout } from "@/components/Layout";
import { Progress } from "@/components/ui/progress";
import { useAuth } from "@/contexts/AuthContext";
import { useLanguage } from "@/contexts/LanguageContext";
import { getGamerProfileSnapshot } from "@/features/arcade/player/gamerProfile";
import { getMissions } from "@/features/arcade/player/missions";
import { ARCADE_ACHIEVEMENTS } from "@/features/arcade/core/achievements";

export default function ArcadePlayerHub() {
  const { pathname } = useLocation(); const { user } = useAuth(); const { lang } = useLanguage(); const ar = lang === "ar";
  const profile = getGamerProfileSnapshot(); const mode = pathname.split("/").pop();
  const name = String(user?.user_metadata?.display_name ?? user?.user_metadata?.name ?? (ar ? "لاعب Visionex" : "Visionex Player"));
  return <Layout><div className="min-h-screen bg-[#070914] text-white"><header className="border-b border-white/10 bg-[radial-gradient(circle_at_20%_0%,rgba(139,92,246,.22),transparent_38%)]"><div className="section-container py-12"><div className="flex flex-col gap-6 sm:flex-row sm:items-center"><div className="grid h-20 w-20 place-items-center overflow-hidden rounded-3xl bg-gradient-to-br from-violet-500 to-cyan-400 text-2xl font-black shadow-xl">{user?.user_metadata?.avatar_url ? <img src={String(user.user_metadata.avatar_url)} alt="" className="h-full w-full object-cover" /> : name.slice(0,1).toUpperCase()}</div><div className="flex-1"><p className="text-sm font-bold text-cyan-300">Visionex Gamer Profile</p><h1 className="mt-1 text-3xl font-black">{name}</h1><div className="mt-4 max-w-xl"><div className="flex justify-between text-xs text-slate-300"><span>{ar ? "المستوى" : "Level"} {profile.level}</span><span>{profile.xp} XP</span></div><Progress value={profile.progress} className="mt-2 h-3" /><p className="mt-1 text-xs text-slate-500">{profile.nextLevel - profile.xp} XP {ar ? "للمستوى التالي" : "to next level"}</p></div></div></div><nav aria-label="Gamer profile" className="mt-8 flex flex-wrap gap-2"><Nav to="/games/profile" active={mode === "profile"} icon={UserRound} label={ar ? "الملف" : "Profile"} /><Nav to="/games/achievements" active={mode === "achievements"} icon={Award} label={ar ? "الإنجازات" : "Achievements"} /><Nav to="/games/challenges" active={mode === "challenges"} icon={CalendarCheck} label={ar ? "التحديات" : "Challenges"} /><Nav to="/games/leaderboard" active={mode === "leaderboard"} icon={Trophy} label={ar ? "الترتيب" : "Leaderboard"} /><Nav to="/games/rewards" active={false} icon={Coins} label={ar ? "مكافآت VX" : "VX Rewards"} /><Nav to="/games/shop" active={false} icon={ShoppingBag} label={ar ? "المتجر" : "Shop"} /></nav></div></header>
    <main className="section-container py-10">{mode === "achievements" ? <Achievements profile={profile} ar={ar} /> : mode === "challenges" ? <Challenges ar={ar} /> : mode === "leaderboard" ? <LeaderboardPanel profile={profile} ar={ar} /> : <ProfileOverview profile={profile} ar={ar} />}</main></div></Layout>;
}

function ProfileOverview({ profile, ar }: { profile:ReturnType<typeof getGamerProfileSnapshot>; ar:boolean }) { return <div className="space-y-8"><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Gamepad2} label={ar ? "مرات اللعب" : "Games played"} value={profile.plays} /><Metric icon={Trophy} label={ar ? "الانتصارات" : "Wins"} value={profile.wins} /><Metric icon={Award} label={ar ? "الإنجازات" : "Achievements"} value={profile.achievements.length} /><Metric icon={Clock3} label={ar ? "وقت اللعب" : "Play time"} value={`${Math.round(profile.totalSeconds/60)}m`} /></dl><div className="grid gap-6 lg:grid-cols-2"><Panel title={ar ? "أفضل النتائج" : "Best scores"}>{profile.bestScores.length ? <ol className="space-y-3">{profile.bestScores.map((item,index) => <li key={item.game.slug} className="flex justify-between rounded-xl bg-white/5 p-3"><span>{index+1}. {item.game.title}</span><strong>{item.data.highScore.toLocaleString()}</strong></li>)}</ol> : <Empty />}</Panel><Panel title={ar ? "التحليلات" : "Player analytics"}><div className="space-y-4"><Row label={ar ? "اللعبة الأكثر استخداماً" : "Most played"} value={profile.mostPlayed?.game.title ?? "—"} /><Row label={ar ? "الألعاب المكتملة" : "Completed games"} value={profile.completions} /><Row label={ar ? "الألعاب المفضلة" : "Favorite games"} value={profile.favorites.length} /></div></Panel></div></div>; }
function Achievements({ profile, ar }: { profile:ReturnType<typeof getGamerProfileSnapshot>; ar:boolean }) { return <section><h2 className="text-3xl font-black">{ar ? "الإنجازات" : "Achievements"}</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{ARCADE_ACHIEVEMENTS.map((item) => { const unlocked=profile.achievements.includes(item.id); return <article key={item.id} className={`rounded-2xl border p-5 ${unlocked ? "border-amber-300/35 bg-amber-300/10" : "border-white/10 bg-white/[.03] opacity-70"}`}><Medal className={`h-8 w-8 ${unlocked ? "text-amber-300" : "text-slate-600"}`} /><h3 className="mt-3 font-black">{item.title}</h3><p className="mt-1 text-sm text-slate-400">{item.description}</p><p className="mt-4 text-xs font-bold">{unlocked ? (ar ? "تم الفتح" : "Unlocked") : (ar ? "مقفل" : "Locked")}</p></article>; })}</div></section>; }
function Challenges({ ar }: { ar:boolean }) { const missions=getMissions(); return <section><h2 className="text-3xl font-black">{ar ? "المهمات والتحديات" : "Missions & challenges"}</h2><div className="mt-6 grid gap-4 lg:grid-cols-2">{missions.map((mission) => <article key={mission.id} className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><div className="flex justify-between"><span className="text-xs font-bold uppercase text-cyan-300">{mission.period}</span><span className="flex items-center gap-1 text-xs text-amber-300"><Zap className="h-3.5 w-3.5" />+{mission.rewardXp} XP</span></div><h3 className="mt-3 font-black">{mission.title}</h3><Progress value={(mission.progress/mission.target)*100} className="mt-4" /><p className="mt-2 text-xs text-slate-400">{mission.progress} / {mission.target}</p></article>)}</div><p className="mt-6 flex gap-2 rounded-xl border border-cyan-300/15 bg-cyan-300/5 p-4 text-sm text-slate-300"><ShieldCheck className="h-5 w-5 shrink-0 text-cyan-300" />{ar ? "XP والمكافآت النهائية تُعتمد من الخادم، وليس من المتصفح." : "Final XP and rewards are validated by the server, never trusted from the browser."}</p></section>; }
function LeaderboardPanel({ profile, ar }: { profile:ReturnType<typeof getGamerProfileSnapshot>; ar:boolean }) { return <section><h2 className="text-3xl font-black">{ar ? "الترتيب العالمي" : "Global leaderboard"}</h2><div className="mt-6 rounded-3xl border border-white/10 bg-white/[.04] p-6"><div className="flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-violet-500/20"><Trophy className="h-7 w-7 text-amber-300" /></div><div><p className="text-sm text-slate-400">{ar ? "نتيجتك المحلية" : "Your local score"}</p><p className="text-2xl font-black">{profile.xp} XP</p></div></div><p className="mt-6 text-sm leading-6 text-slate-400">{ar ? "جداول اليوم والأسبوع والشهر وكل الوقت موجودة في Migration المرحلة العاشرة. تظهر البيانات العالمية بعد تطبيق Migration وتوليد أنواع Supabase الجديدة." : "Daily, weekly, monthly, and all-time boards are defined in the Phase 10 migration. Global data appears after applying the migration and regenerating Supabase types."}</p></div></section>; }
function Nav({to,active,icon:Icon,label}:{to:string;active:boolean;icon:typeof UserRound;label:string}) { return <Link to={to} aria-current={active ? "page" : undefined} className={`flex items-center gap-2 rounded-xl px-4 py-2 text-sm font-bold ${active ? "bg-white text-slate-950" : "bg-white/5 text-slate-300 hover:bg-white/10"}`}><Icon className="h-4 w-4" />{label}</Link>; }
function Metric({icon:Icon,label,value}:{icon:typeof Gamepad2;label:string;value:string|number}) { return <div className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><dt className="flex items-center gap-2 text-sm text-slate-400"><Icon className="h-4 w-4 text-violet-300" />{label}</dt><dd className="mt-3 text-3xl font-black">{value}</dd></div>; }
function Panel({title,children}:{title:string;children:ReactNode}) { return <section className="rounded-2xl border border-white/10 bg-white/[.04] p-6"><h2 className="text-xl font-black">{title}</h2><div className="mt-5">{children}</div></section>; }
function Row({label,value}:{label:string;value:string|number}) { return <div className="flex justify-between border-b border-white/10 pb-3"><span className="text-slate-400">{label}</span><strong>{value}</strong></div>; }
function Empty() { return <p className="text-sm text-slate-500">No results yet.</p>; }
