import { createClient } from "npm:@supabase/supabase-js@2";
import { getCorsHeaders } from "../_shared/cors.ts";
import { createEmbedding } from "../_shared/aiProvider.ts";
import servicesCatalog from "../_shared/data/servicesCatalog.json" with { type: "json" };

/**
 * Services are a code catalogue, not a table — the approved Phase 1 decision
 * was to index it rather than duplicate it into the database. This snapshot is
 * generated by `npx vite-node scripts/generate-services-index.ts` and kept in
 * step by src/test/services-index.test.ts.
 *
 * It is indexed into the same `ai_embeddings` table under the virtual source
 * name `services`, so retrieval stays one system.
 */
const SERVICES_SOURCE = "services";

interface IndexedService {
  id: string;
  text: string;
}

// Which tables get embedded and how their searchable text is built.
//
// Phase 1 widened this from two tables to the user-facing domains the AI Core
// is expected to know about. Three deliberate exclusions:
//
//  - `library_books` already carries its own `embedding` column and is served
//    by library-semantic-search / library-embed-book. Indexing it here too
//    would be a second semantic system for the same rows, which the spec
//    forbids. Cross-domain queries reach the library through that index.
//  - Anything under `kids_*` that identifies a child. Only the public
//    catalogue of games is indexed, never progress, messages or profiles.
//  - Tables with no user-facing text worth retrieving.
//
// `filter` keeps unpublished and inactive rows out of the index, so the AI
// cannot recommend something a visitor cannot reach.
interface SourceConfig {
  columns: string;
  toText: (r: Record<string, unknown>) => string;
  /** Applied as .eq() pairs; keeps drafts and disabled rows unindexed. */
  filter?: Record<string, unknown>;
}

const SOURCES: Record<string, SourceConfig> = {
  products: {
    columns: "id, name, description, category, store_type",
    toText: (r) => [r.name, r.category, r.store_type, r.description].filter(Boolean).join(". "),
  },
  content_items: {
    columns: "id, title, description, category, type, level",
    toText: (r) => [r.title, r.category, r.type, r.level, r.description].filter(Boolean).join(". "),
    filter: { published: true },
  },
  academy_courses: {
    columns: "id, title, description, subject, category, level, difficulty, tags, learning_outcomes",
    toText: (r) =>
      [r.title, r.subject, r.category, r.level, r.difficulty, r.description,
       Array.isArray(r.tags) ? (r.tags as string[]).join(", ") : null,
       Array.isArray(r.learning_outcomes) ? (r.learning_outcomes as string[]).join(". ") : null]
        .filter(Boolean).join(". "),
    filter: { published: true },
  },
  kids_games: {
    columns: "id, title, description, difficulty, age_range, tags, accessibility_features, status",
    toText: (r) =>
      [r.title, r.description, r.difficulty, r.age_range,
       Array.isArray(r.tags) ? (r.tags as string[]).join(", ") : null,
       Array.isArray(r.accessibility_features) ? (r.accessibility_features as string[]).join(", ") : null]
        .filter(Boolean).join(". "),
    filter: { status: "published" },
  },
  simulations: {
    columns: "id, title, description, difficulty, subcategory",
    toText: (r) => [r.title, r.subcategory, r.difficulty, r.description].filter(Boolean).join(". "),
    filter: { published: true },
  },
  tv_channels: {
    columns: "id, name, name_ar, description, description_ar, country, language",
    toText: (r) => [r.name, r.name_ar, r.country, r.language, r.description, r.description_ar].filter(Boolean).join(". "),
    filter: { is_active: true },
  },
  radio_stations: {
    columns: "id, name, name_ar, description, description_ar, country, language",
    toText: (r) => [r.name, r.name_ar, r.country, r.language, r.description, r.description_ar].filter(Boolean).join(". "),
    filter: { is_active: true },
  },
  communities: {
    columns: "id, name, description, category",
    toText: (r) => [r.name, r.category, r.description].filter(Boolean).join(". "),
  },
  events: {
    columns: "id, title, description, event_type, location",
    toText: (r) => [r.title, r.event_type, r.location, r.description].filter(Boolean).join(". "),
  },
  jobs: {
    columns: "id, title, description, job_type, location, experience_level, skills_required, accessibility_friendly",
    toText: (r) =>
      [r.title, r.job_type, r.location, r.experience_level,
       Array.isArray(r.skills_required) ? (r.skills_required as string[]).join(", ") : null,
       r.accessibility_friendly ? "accessibility friendly" : null, r.description]
        .filter(Boolean).join(". "),
    filter: { status: "open" },
  },
};

const BATCH = 50;

Deno.serve(async (req) => {
  const corsHeaders = getCorsHeaders(req);
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // ── Admin only ─────────────────────────────────────────────────────
    const authHeader = req.headers.get("Authorization");
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader || "" } } },
    );
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    const { data: roleData } = await supabase
      .from("user_roles").select("role").eq("user_id", user.id).eq("role", "admin").maybeSingle();
    if (!roleData) {
      return new Response(JSON.stringify({ error: "Admin access required" }), {
        status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { source_table } = await req.json().catch(() => ({}));
    const requested: string[] = source_table
      ? [source_table]
      : [...Object.keys(SOURCES), SERVICES_SOURCE];

    for (const t of requested) {
      if (!SOURCES[t] && t !== SERVICES_SOURCE) {
        return new Response(JSON.stringify({ error: `Unknown source_table: ${t}` }), {
          status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
    }

    const tables = requested.filter((t) => t !== SERVICES_SOURCE);
    const indexServices = requested.includes(SERVICES_SOURCE);

    const service = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );

    const summary: Record<string, number> = {};

    for (const table of tables) {
      const cfg = SOURCES[table];
      let query = service.from(table).select(cfg.columns).limit(2000);
      for (const [column, value] of Object.entries(cfg.filter ?? {})) {
        query = query.eq(column, value);
      }
      const { data: rows, error } = await query;
      // One table failing — a column renamed, a table not yet deployed — must
      // not abandon the tables that would have indexed fine.
      if (error) {
        console.error(`[embed-content] skipping ${table}:`, error.message);
        summary[table] = -1;
        continue;
      }
      if (!rows || rows.length === 0) { summary[table] = 0; continue; }

      let embedded = 0;
      for (let i = 0; i < rows.length; i += BATCH) {
        const chunk = rows.slice(i, i + BATCH) as Array<Record<string, unknown>>;
        const texts = chunk.map((r) => cfg.toText(r).slice(0, 6000));
        const vectors = await createEmbedding(texts);

        const upserts = chunk.map((r, j) => ({
          source_table: table,
          source_id: r.id,
          content: texts[j],
          embedding: vectors[j],
          updated_at: new Date().toISOString(),
        }));
        const { error: upErr } = await service
          .from("ai_embeddings")
          .upsert(upserts, { onConflict: "source_table,source_id" });
        if (upErr) throw upErr;
        embedded += upserts.length;
      }
      summary[table] = embedded;
    }

    // Services come from the committed catalogue snapshot rather than a table,
    // but land in the same ai_embeddings store under the `services` source, so
    // one semantic search covers them alongside everything else.
    if (indexServices) {
      const services = servicesCatalog as IndexedService[];
      let embedded = 0;
      for (let i = 0; i < services.length; i += BATCH) {
        const chunk = services.slice(i, i + BATCH);
        const vectors = await createEmbedding(chunk.map((s) => s.text.slice(0, 6000)));
        const { error: upErr } = await service.from("ai_embeddings").upsert(
          chunk.map((s, j) => ({
            source_table: SERVICES_SOURCE,
            source_id: s.id,
            content: s.text,
            embedding: vectors[j],
            updated_at: new Date().toISOString(),
          })),
          { onConflict: "source_table,source_id" },
        );
        if (upErr) throw upErr;
        embedded += chunk.length;
      }
      summary[SERVICES_SOURCE] = embedded;
    }

    return new Response(JSON.stringify({ ok: true, embedded: summary }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("embed-content error:", e);
    return new Response(
      JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }
});
