export type QuizQuestion={question:string;answers:string[];correct:number};
export type QuizBank={title:string;questions:QuizQuestion[]};
export const ADVANCED_QUIZ_BANKS:Record<string,QuizBank>={
 "technology-quiz":{title:"Technology Quiz",questions:[{question:"What does CPU stand for?",answers:["Central Processing Unit","Computer Personal Utility","Core Program User","Central Power Unit"],correct:0},{question:"Which protocol secures web traffic?",answers:["FTP","HTTP","HTTPS","SMTP"],correct:2},{question:"What is two-factor authentication designed to improve?",answers:["Screen brightness","Account security","Download speed","File size"],correct:1},{question:"Which storage keeps data without power?",answers:["RAM","CPU cache","SSD","Register"],correct:2}]},
 "nature-quiz":{title:"Nature Quiz",questions:[{question:"Which process lets plants make food from light?",answers:["Respiration","Photosynthesis","Pollination","Evaporation"],correct:1},{question:"What is a group of wolves called?",answers:["Herd","School","Pack","Colony"],correct:2},{question:"Which ecosystem receives very little rainfall?",answers:["Rainforest","Wetland","Desert","Reef"],correct:2},{question:"Bees help flowering plants mainly through what?",answers:["Migration","Pollination","Hibernation","Camouflage"],correct:1}]},
 "space-quiz":{title:"Space Quiz",questions:[{question:"Which planet is closest to the Sun?",answers:["Venus","Earth","Mercury","Mars"],correct:2},{question:"What galaxy contains our solar system?",answers:["Andromeda","Milky Way","Sombrero","Whirlpool"],correct:1},{question:"What is Earth's natural satellite?",answers:["Moon","Titan","Europa","Phobos"],correct:0},{question:"A light-year measures what?",answers:["Time","Mass","Distance","Temperature"],correct:2}]},
 "sports-quiz":{title:"Sports Quiz",questions:[{question:"How many players does a football team field at once?",answers:["9","10","11","12"],correct:2},{question:"Which sport uses a shuttlecock?",answers:["Tennis","Badminton","Squash","Table tennis"],correct:1},{question:"How many points is a basketball free throw worth?",answers:["1","2","3","4"],correct:0},{question:"Which swimming stroke shares its name with an insect?",answers:["Freestyle","Backstroke","Butterfly","Breaststroke"],correct:2}]},
};
export function validateQuizBank(bank:QuizBank){return bank.questions.length>=4&&bank.questions.every(item=>item.answers.length===4&&item.correct>=0&&item.correct<item.answers.length&&new Set(item.answers).size===item.answers.length)}
