export type Suit="hearts"|"diamonds"|"clubs"|"spades";export type Card={id:string;rank:number;suit:Suit};export type SolitaireRule="klondike"|"spider"|"freecell";
export const isRed=(suit:Suit)=>suit==="hearts"||suit==="diamonds";
export function canStack(card:Card,target:Card|undefined,rule:SolitaireRule){if(!target)return true;if(card.rank!==target.rank-1)return false;return rule==="spider"?card.suit===target.suit:isRed(card.suit)!==isRed(target.suit)}
export function moveCard(columns:Card[][],from:number,to:number,rule:SolitaireRule){if(from===to||!columns[from]?.length||!columns[to])return columns;const card=columns[from][columns[from].length-1],target=columns[to][columns[to].length-1];if(!canStack(card,target,rule))return columns;const next=columns.map(column=>[...column]);next[from].pop();next[to].push(card);return next}
export function dealSolitaire(rule:SolitaireRule):Card[][]{const suits:Suit[]=rule==="spider"?["spades","spades","spades","spades"]:["hearts","clubs","diamonds","spades"];return [[7,6],[8,7],[9,8],[10,9]].map((ranks,column)=>ranks.map((rank,index)=>({id:`${rule}-${column}-${index}`,rank,suit:suits[(column+index)%suits.length]})))}
export type MahjongTile={id:string;symbol:string;row:number;column:number;removed:boolean};
export function mahjongBoard():MahjongTile[]{const symbols=["Bamboo","Dragon","Circle","Wind","Bamboo","Dragon","Circle","Wind"];return symbols.map((symbol,index)=>({id:`tile-${index}`,symbol,row:Math.floor(index/4),column:index%4,removed:false}))}
export function isMahjongFree(board:MahjongTile[],tile:MahjongTile){if(tile.removed)return false;const left=board.find(other=>!other.removed&&other.row===tile.row&&other.column===tile.column-1),right=board.find(other=>!other.removed&&other.row===tile.row&&other.column===tile.column+1);return!left||!right}
export function removeMahjongPair(board:MahjongTile[],firstId:string,secondId:string){const first=board.find(tile=>tile.id===firstId),second=board.find(tile=>tile.id===secondId);if(!first||!second||first.id===second.id||first.symbol!==second.symbol||!isMahjongFree(board,first)||!isMahjongFree(board,second))return board;return board.map(tile=>tile.id===firstId||tile.id===secondId?{...tile,removed:true}:tile)}
