-- "New conversation", without losing the old one.
--
-- The assistant already had memory: `whatsapp_messages` is the transcript, and
-- the webhook replays the recent turns plus a rolling summary. What it had no
-- concept of was a *thread* — a point the sender can draw a line under and
-- start again, which is the one thing every chat assistant offers and this one
-- could not.
--
-- Two columns, and no deletion. Starting a new conversation moves the line;
-- everything before it stays exactly where it was, still readable by the team
-- triaging escalations, still under the retention policy it already had. That
-- matters more here than it would elsewhere: these rows are how a support
-- conversation is reconstructed when a customer says "I told you last week".
--
-- The replay queries filter on `created_at >= ai_thread_started_at`, which the
-- existing (conversation_id, created_at) index already serves.

ALTER TABLE public.whatsapp_conversations
  ADD COLUMN IF NOT EXISTS ai_thread_id uuid NOT NULL DEFAULT gen_random_uuid(),
  ADD COLUMN IF NOT EXISTS ai_thread_started_at timestamptz NOT NULL DEFAULT now();

COMMENT ON COLUMN public.whatsapp_conversations.ai_thread_id IS
  'Identifies the current AI conversation. Regenerated by "new conversation"; nothing is deleted when it changes.';

COMMENT ON COLUMN public.whatsapp_conversations.ai_thread_started_at IS
  'The line the sender drew. History replay and the rolling summary read only messages at or after this moment.';

-- A summary describes the thread it was written for. When the thread moves the
-- summary is stale by definition, so the webhook clears it in the same update —
-- this backfill only makes existing rows consistent with that rule from the
-- start, rather than letting an old summary leak into a brand new conversation.
UPDATE public.whatsapp_conversations
   SET ai_thread_started_at = COALESCE(created_at, now())
 WHERE ai_thread_started_at > COALESCE(last_message_at, now());
