import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {useLocation} from "react-router-dom";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {useGameEconomy} from "@/components/game/GameEconomyGate";
import {gameManager} from "@/features/arcade/core/gameManager";
import {accessibilityAudio} from "@/features/arcade/audio/AccessibilityAudioLayer";
import {AUDIO_MAZE,chooseTicMove,createMathQuestion,moveMaze,ticWinner,type Mark,type MazePoint} from "@/lib/games/arcadeBatchTwoEngines";
import {ADVANCED_QUIZ_BANKS} from "@/lib/games/advancedQuizBanks";

const panel="mx-auto max-w-3xl space-y-6 p-4 sm:p-8";
const say=(message:string)=>accessibilityAudio.announce(message,"status");

export function TicTacToe(){const [board,setBoard]=useState<Mark[]>(Array(9).fill(null));const [message,setMessage]=useState("Your turn as X");const [done,setDone]=useState(false);const {settleGameResult}=useGameEconomy();
 const reset=()=>{setBoard(Array(9).fill(null));setMessage("Your turn as X");setDone(false)};
 const play=(index:number)=>{if(done||board[index])return;const next=[...board];next[index]="X";if(ticWinner(next)){setBoard(next);setMessage("You won");setDone(true);gameManager.recordScore(300);void settleGameResult("win","Tic Tac Toe");return}const ai=chooseTicMove(next);if(ai<0){setBoard(next);setMessage("Draw");setDone(true);void settleGameResult("draw","Tic Tac Toe");return}next[ai]="O";setBoard(next);if(ticWinner(next)){setMessage("Computer won");setDone(true);void settleGameResult("loss","Tic Tac Toe")}else setMessage(`Computer selected cell ${ai+1}. Your turn`)};
 return <section className={panel}><header className="flex items-center justify-between"><p role="status" aria-live="polite" className="font-bold">{message}</p><Button variant="outline" onClick={reset}>New match</Button></header><div role="grid" aria-label="Tic tac toe board" className="mx-auto grid max-w-md grid-cols-3 gap-3">{board.map((mark,index)=><button key={index} role="gridcell" onClick={()=>play(index)} aria-label={`Cell ${index+1}: ${mark??"empty"}`} className="grid aspect-square place-items-center rounded-2xl border-2 border-violet-300/30 bg-slate-900 text-5xl font-black text-cyan-300 hover:bg-slate-800">{mark}</button>)}</div><p className="text-sm text-muted-foreground">Place three X marks in a row before the tactical computer places three O marks.</p></section>}

const texts=["Accessible design makes digital experiences work better for everyone.","Practice builds speed, accuracy, confidence, and consistent keyboard control.","Visionex Arcade combines learning, strategy, and inclusive play in one platform."];
export function TypingSpeed(){const [text,setText]=useState(texts[0]);const [value,setValue]=useState("");const [started,setStarted]=useState<number>();const [result,setResult]=useState("");const {settleGameResult}=useGameEconomy();
 const reset=()=>{setText(texts[Math.floor(Math.random()*texts.length)]);setValue("");setStarted(undefined);setResult("")};
 const update=(next:string)=>{if(!started)setStarted(Date.now());setValue(next);if(next===text){const minutes=Math.max((Date.now()-(started??Date.now()))/60000,1/60);const words=Math.round(text.split(" ").length/minutes);const summary=`${words} words per minute with 100% accuracy`;setResult(summary);gameManager.recordScore(words);say(summary);void settleGameResult("win","Typing Speed")}};
 return <section className={panel}><p className="rounded-2xl bg-slate-900 p-6 text-lg leading-8 text-white" aria-label="Text to type">{text}</p><label className="block space-y-2"><span className="font-bold">Type the text exactly</span><textarea autoFocus value={value} onChange={e=>update(e.target.value)} className="min-h-36 w-full rounded-xl border p-4 text-lg" aria-describedby="typing-result" /></label><p id="typing-result" role="status" aria-live="polite" className="font-bold text-emerald-600">{result}</p><Button variant="outline" onClick={reset}>New text</Button></section>}

export function MathChallenge(){const [level,setLevel]=useState(1);const [question,setQuestion]=useState(()=>createMathQuestion(1));const [answer,setAnswer]=useState("");const [message,setMessage]=useState("Solve the equation");const {settleGameResult}=useGameEconomy();
 const submit=()=>{if(Number(answer)===question.answer){const next=level+1;gameManager.recordScore(level*100);if(next>10){setMessage("Ten equations complete!");void settleGameResult("win","Math Challenge");return}setLevel(next);setQuestion(createMathQuestion(next));setAnswer("");setMessage("Correct. Next equation") }else{setMessage("Not yet. Check the operation and try again");say("Incorrect. Try again")}};
 return <section className={panel}><p className="text-center text-sm font-bold text-violet-600">Level {level} of 10</p><div className="rounded-3xl bg-slate-950 p-12 text-center text-5xl font-black text-white" aria-label={`${question.left} ${question.operation} ${question.right}`}>{question.left} {question.operation} {question.right}</div><form onSubmit={e=>{e.preventDefault();submit()}} className="mx-auto flex max-w-md gap-3"><Input inputMode="numeric" value={answer} onChange={e=>setAnswer(e.target.value)} aria-label="Answer" autoFocus/><Button type="submit">Check</Button></form><p role="status" aria-live="polite" className="text-center font-semibold">{message}</p></section>}

const colors=["Cyan","Violet","Amber","Emerald"] as const;
export function SimonSays(){const [sequence,setSequence]=useState<number[]>([]);const [input,setInput]=useState<number[]>([]);const [message,setMessage]=useState("Start a memory sequence");const [locked,setLocked]=useState(true);const timers=useRef<number[]>([]);const {settleGameResult}=useGameEconomy();
 useEffect(()=>()=>timers.current.forEach(clearTimeout),[]);
 const present=(next:number[])=>{setLocked(true);setInput([]);next.forEach((color,i)=>timers.current.push(window.setTimeout(()=>say(colors[color]),500+i*700)));timers.current.push(window.setTimeout(()=>{setLocked(false);setMessage(`Repeat ${next.length} signals`)},500+next.length*700))};
 const start=()=>{const next=[Math.floor(Math.random()*4)];setSequence(next);setMessage("Listen to the sequence");present(next)};
 const press=(color:number)=>{if(locked)return;const next=[...input,color];if(sequence[next.length-1]!==color){setMessage("Sequence mismatch. Start again");setLocked(true);void settleGameResult("loss","Simon Says");return}if(next.length===sequence.length){gameManager.recordScore(sequence.length*100);if(sequence.length>=6){setMessage("Six rounds complete!");setLocked(true);void settleGameResult("win","Simon Says");return}const expanded=[...sequence,Math.floor(Math.random()*4)];setSequence(expanded);setMessage("Correct. Listen to the longer sequence");present(expanded)}else setInput(next)};
 return <section className={panel}><p role="status" aria-live="polite" className="text-center font-bold">{message}</p><div className="grid grid-cols-2 gap-4">{colors.map((color,index)=><button key={color} disabled={locked} onClick={()=>press(index)} className={`aspect-[2/1] rounded-3xl text-xl font-black text-white disabled:opacity-50 ${["bg-cyan-600","bg-violet-600","bg-amber-600","bg-emerald-600"][index]}`} aria-label={color}>{color}</button>)}</div><Button onClick={start} className="w-full">Start sequence</Button></section>}

type Q={question:string;answers:string[];correct:number};
const banks:Record<string,{title:string;questions:Q[]}>= {
 trivia:{title:"Trivia",questions:[{question:"Which planet is known as the Red Planet?",answers:["Venus","Mars","Jupiter","Mercury"],correct:1},{question:"How many sides does a hexagon have?",answers:["Five","Six","Seven","Eight"],correct:1},{question:"Which ocean is the largest?",answers:["Atlantic","Indian","Pacific","Arctic"],correct:2}]},
 "geography-quiz":{title:"Geography Quiz",questions:[{question:"What is the capital of Japan?",answers:["Seoul","Tokyo","Kyoto","Osaka"],correct:1},{question:"The Nile flows into which sea?",answers:["Red Sea","Mediterranean Sea","Arabian Sea","Black Sea"],correct:1},{question:"Which continent contains Peru?",answers:["Asia","Africa","South America","Europe"],correct:2}]},
 "science-quiz":{title:"Science Quiz",questions:[{question:"What gas do plants absorb?",answers:["Oxygen","Carbon dioxide","Hydrogen","Nitrogen"],correct:1},{question:"What is H2O?",answers:["Salt","Water","Oxygen","Helium"],correct:1},{question:"Which force keeps planets in orbit?",answers:["Friction","Gravity","Magnetism","Pressure"],correct:1}]},
 "history-quiz":{title:"History Quiz",questions:[{question:"Which civilization built Machu Picchu?",answers:["Roman","Inca","Maya","Greek"],correct:1},{question:"The printing press is associated with whom?",answers:["Galileo","Gutenberg","Newton","Edison"],correct:1},{question:"Ancient Alexandria was famous for its what?",answers:["Library","Wall","Pyramid","Arena"],correct:0}]},
 ...ADVANCED_QUIZ_BANKS,
};
export function KnowledgeQuiz(){const slug=useLocation().pathname.split("/").pop()!;const bank=banks[slug]??banks.trivia;const [index,setIndex]=useState(0);const [score,setScore]=useState(0);const [message,setMessage]=useState("Choose the best answer");const {settleGameResult}=useGameEconomy();const question=bank.questions[index];
 const choose=(answer:number)=>{const correct=answer===question.correct;const nextScore=score+(correct?100:0);setScore(nextScore);if(index===bank.questions.length-1){gameManager.recordScore(nextScore);setMessage(`${correct?"Correct":"Incorrect"}. Quiz complete: ${nextScore} points`);void settleGameResult(nextScore>=200?"win":"loss",bank.title)}else{setMessage(correct?"Correct":"Incorrect");setIndex(index+1)}};
 return <section className={panel}><header className="flex justify-between"><span>Question {index+1} / {bank.questions.length}</span><strong>{score} points</strong></header><h2 className="rounded-3xl bg-slate-950 p-8 text-center text-2xl font-black text-white">{question.question}</h2><div className="grid gap-3 sm:grid-cols-2">{question.answers.map((answer,i)=><Button key={answer} variant="outline" className="h-auto min-h-16 whitespace-normal p-4 text-base" onClick={()=>choose(i)}>{i+1}. {answer}</Button>)}</div><p role="status" aria-live="polite" className="text-center font-bold">{message}</p></section>}

const MAZE_GOAL={row:6,column:6} as const;
export function BlindMaze(){const [point,setPoint]=useState<MazePoint>({row:0,column:0});const [moves,setMoves]=useState(0);const {settleGameResult}=useGameEconomy();
 const move=useCallback((direction:"up"|"down"|"left"|"right")=>{setPoint(current=>{const next=moveMaze(current,direction);const changed=next!==current;setMoves(value=>value+1);say(changed?`${direction}. Row ${next.row+1}, column ${next.column+1}`:`Wall ${direction}`);if(next.row===MAZE_GOAL.row&&next.column===MAZE_GOAL.column){gameManager.recordScore(Math.max(100,1000-moves*10));void settleGameResult("win","Blind Maze")}return next})},[moves,settleGameResult]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{const direction=({ArrowUp:"up",ArrowDown:"down",ArrowLeft:"left",ArrowRight:"right"} as const)[e.key as "ArrowUp"];if(direction){e.preventDefault();move(direction)}};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)},[move]);
 return <section className={panel}><p role="status" aria-live="polite" className="text-center font-bold">Position: row {point.row+1}, column {point.column+1}. Moves: {moves}</p><div role="grid" aria-label="Maze board" className="grid grid-cols-7 gap-1 rounded-2xl bg-slate-900 p-3">{AUDIO_MAZE.flatMap((row,r)=>row.map((wall,c)=><div key={`${r}-${c}`} role="gridcell" aria-label={wall?"Wall":r===MAZE_GOAL.row&&c===MAZE_GOAL.column?"Goal":r===point.row&&c===point.column?"Player":"Path"} className={`aspect-square rounded ${wall?"bg-slate-700":r===point.row&&c===point.column?"bg-cyan-400":r===MAZE_GOAL.row&&c===MAZE_GOAL.column?"bg-emerald-400":"bg-white/10"}`}/>))}</div><div className="grid grid-cols-3 gap-2"><span/><Button onClick={()=>move("up")}>Up</Button><span/><Button onClick={()=>move("left")}>Left</Button><Button onClick={()=>move("down")}>Down</Button><Button onClick={()=>move("right")}>Right</Button></div><p className="text-sm text-muted-foreground">Navigate from the top-left to the bottom-right. Audio status reports every successful move and wall.</p></section>}
