import {useEffect,useMemo,useRef,useState} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {useGameEconomy} from "@/components/game/GameEconomyGate";
import {gameManager} from "@/features/arcade/core/gameManager";
import {accessibilityAudio} from "@/features/arcade/audio/AccessibilityAudioLayer";
import {NONOGRAM_SOLUTION,SUDOKU_PUZZLE,WORD_GRID,WORD_TARGETS,nonogramComplete,scoreMastermind,validSudokuMove,wordExists} from "@/lib/games/arcadeBatchThreeEngines";
const panel="mx-auto max-w-3xl space-y-6 p-4 sm:p-8";const say=(message:string)=>accessibilityAudio.announce(message,"status");

export function Sudoku(){const [board,setBoard]=useState(()=>SUDOKU_PUZZLE.map(row=>[...row]));const [message,setMessage]=useState("Fill every empty cell");const {settleGameResult}=useGameEconomy();const set=(r:number,c:number,text:string)=>{const value=Number(text);if(!value){setBoard(current=>current.map((row,rr)=>row.map((cell,cc)=>rr===r&&cc===c?0:cell)));return}if(!validSudokuMove(r,c,value)){setMessage(`Row ${r+1}, column ${c+1}: ${value} conflicts with the solution`);say("Incorrect number");return}const next=board.map(row=>[...row]);next[r][c]=value;setBoard(next);setMessage("Correct number");const complete=next.every((row,rr)=>row.every((value,cc)=>validSudokuMove(rr,cc,value)));if(complete){gameManager.recordScore(810);void settleGameResult("win","Sudoku")}};
 return <section className={panel}><p role="status" aria-live="polite" className="font-bold">{message}</p><div role="grid" aria-label="Sudoku grid" className="grid grid-cols-9 overflow-hidden rounded-xl border-4 border-slate-900">{board.flatMap((row,r)=>row.map((value,c)=>{const fixed=SUDOKU_PUZZLE[r][c]!==0;return fixed?<div key={`${r}-${c}`} role="gridcell" aria-label={`Row ${r+1}, column ${c+1}: fixed ${value}`} className="grid aspect-square place-items-center border bg-slate-200 font-black text-slate-900">{value}</div>:<input key={`${r}-${c}`} value={value||""} onChange={e=>set(r,c,e.target.value.slice(-1))} inputMode="numeric" aria-label={`Row ${r+1}, column ${c+1}`} className="aspect-square min-w-0 border bg-white text-center font-bold text-violet-700 focus:z-10 focus:ring-2 focus:ring-violet-500"/>}))}</div><p className="text-sm text-muted-foreground">Enter numbers 1–9. Every row, column, and three-by-three box must contain each number once.</p></section>}

export function Nonogram(){const [cells,setCells]=useState(()=>Array.from({length:5},()=>Array(5).fill(false)));const [message,setMessage]=useState("Use the clues to reveal the picture");const {settleGameResult}=useGameEconomy();const rowClues=useMemo(()=>["1 1 1","5","3","1","1"],[]);const colClues=useMemo(()=>["2","3","5","3","2"],[]);const toggle=(r:number,c:number)=>{const next=cells.map(row=>[...row]);next[r][c]=!next[r][c];setCells(next);if(nonogramComplete(next)){setMessage("Picture complete");gameManager.recordScore(500);void settleGameResult("win","Nonogram")}};
 return <section className={panel}><p role="status" aria-live="polite" className="font-bold">{message}</p><div className="mx-auto grid max-w-lg grid-cols-[4rem_repeat(5,1fr)] gap-1"><span/><>{colClues.map((clue,i)=><span key={i} className="text-center text-sm font-bold">{clue}</span>)}</>{cells.map((row,r)=><div key={r} className="contents"><span className="self-center text-end text-sm font-bold pe-2">{rowClues[r]}</span>{row.map((filled,c)=><button key={c} onClick={()=>toggle(r,c)} aria-label={`Row ${r+1}, column ${c+1}: ${filled?"filled":"empty"}`} aria-pressed={filled} className={`aspect-square rounded border-2 ${filled?"border-cyan-300 bg-cyan-600":"border-slate-300 bg-white"}`}/>)}</div>)}</div><p className="text-sm text-muted-foreground">Each clue describes consecutive filled cells in its row or column.</p></section>}

const palette=["Cyan","Violet","Amber","Emerald","Rose","Blue"];
export function Mastermind(){const secret=useRef([0,3,1,4]);const [guess,setGuess]=useState([0,0,0,0]);const [attempts,setAttempts]=useState<{guess:number[];exact:number;color:number}[]>([]);const [message,setMessage]=useState("Decode the four-color sequence");const {settleGameResult}=useGameEconomy();const submit=()=>{const result=scoreMastermind(secret.current,guess);const next=[...attempts,{guess:[...guess],...result}];setAttempts(next);if(result.exact===4){setMessage("Code solved");gameManager.recordScore(Math.max(100,1000-next.length*100));void settleGameResult("win","Mastermind")}else if(next.length>=8){setMessage("Eight attempts used");void settleGameResult("loss","Mastermind")}else setMessage(`${result.exact} exact, ${result.color} correct colors in other positions`)};
 return <section className={panel}><p role="status" aria-live="polite" className="font-bold">{message}</p><div className="grid grid-cols-4 gap-3">{guess.map((value,index)=><label key={index} className="space-y-2"><span className="text-sm font-bold">Position {index+1}</span><select value={value} onChange={e=>setGuess(current=>current.map((item,i)=>i===index?Number(e.target.value):item))} className="h-12 w-full rounded border bg-white px-2">{palette.map((color,i)=><option key={color} value={i}>{color}</option>)}</select></label>)}</div><Button onClick={submit} disabled={attempts.length>=8} className="w-full">Submit code</Button><ol className="space-y-2">{attempts.map((attempt,i)=><li key={i} className="rounded-lg bg-slate-100 p-3 text-sm"><strong>Attempt {i+1}:</strong> {attempt.guess.map(value=>palette[value]).join(", ")} — {attempt.exact} exact, {attempt.color} misplaced</li>)}</ol></section>}

export function WordSearch(){const [found,setFound]=useState<string[]>([]);const [word,setWord]=useState("");const [message,setMessage]=useState("Find the five listed words");const {settleGameResult}=useGameEconomy();const submit=()=>{const normalized=word.trim().toUpperCase();if(!WORD_TARGETS.includes(normalized as typeof WORD_TARGETS[number])||!wordExists(normalized)){setMessage("That word is not in this puzzle");return}if(found.includes(normalized)){setMessage("Already found");return}const next=[...found,normalized];setFound(next);setWord("");setMessage(`${normalized} found`);gameManager.recordScore(next.length*100);if(next.length===WORD_TARGETS.length)void settleGameResult("win","Word Search")};
 return <section className={panel}><div className="grid grid-cols-8 gap-1 rounded-xl bg-slate-900 p-3" role="grid" aria-label="Eight by eight letter grid">{WORD_GRID.flatMap((row,r)=>[...row].map((letter,c)=><span key={`${r}-${c}`} role="gridcell" aria-label={`Row ${r+1}, column ${c+1}: ${letter}`} className="grid aspect-square place-items-center rounded bg-white font-black text-slate-900">{letter}</span>))}</div><p>Find: {WORD_TARGETS.map(target=><span key={target} className={`me-3 font-bold ${found.includes(target)?"text-emerald-600 line-through":""}`}>{target}</span>)}</p><form onSubmit={e=>{e.preventDefault();submit()}} className="flex gap-3"><Input value={word} onChange={e=>setWord(e.target.value)} aria-label="Found word"/><Button type="submit">Check</Button></form><p role="status" aria-live="polite" className="font-bold">{message}</p></section>}

const colorRounds=[{word:"BLUE",ink:"text-rose-600",answer:"Rose"},{word:"GREEN",ink:"text-violet-600",answer:"Violet"},{word:"RED",ink:"text-cyan-600",answer:"Cyan"},{word:"YELLOW",ink:"text-emerald-600",answer:"Emerald"}];
export function ColorMatch(){const [round,setRound]=useState(0);const [score,setScore]=useState(0);const [message,setMessage]=useState("Choose the ink color, not the written word");const {settleGameResult}=useGameEconomy();const current=colorRounds[round];const choose=(answer:string)=>{const correct=answer===current.answer;const nextScore=score+(correct?100:0);setScore(nextScore);if(round===colorRounds.length-1){setMessage(`Challenge complete: ${nextScore} points`);gameManager.recordScore(nextScore);void settleGameResult(nextScore>=300?"win":"loss","Color Match")}else{setMessage(correct?"Correct":"Incorrect");setRound(round+1)}};
 return <section className={panel}><header className="flex justify-between"><span>Round {round+1} / 4</span><strong>{score} points</strong></header><div className={`rounded-3xl bg-slate-100 p-16 text-center text-6xl font-black ${current.ink}`}>{current.word}</div><div className="grid grid-cols-2 gap-3">{["Rose","Violet","Cyan","Emerald"].map(color=><Button key={color} variant="outline" className="min-h-16 text-lg" onClick={()=>choose(color)}>{color}</Button>)}</div><p role="status" aria-live="polite" className="text-center font-bold">{message}</p></section>}

const directions=["left","right","front","behind"] as const;
export function AudioDirection(){const [round,setRound]=useState(0);const [target,setTarget]=useState<typeof directions[number]>("left");const [score,setScore]=useState(0);const [message,setMessage]=useState("Start the direction challenge");const {settleGameResult}=useGameEconomy();const play=()=>{const next=directions[Math.floor(Math.random()*directions.length)];setTarget(next);say(`Sound is ${next}`);setMessage("Choose the announced direction")};const choose=(direction:string)=>{const correct=direction===target;const nextScore=score+(correct?100:0);setScore(nextScore);if(round>=4){setMessage(`Five rounds complete: ${nextScore}`);gameManager.recordScore(nextScore);void settleGameResult(nextScore>=400?"win":"loss","Audio Direction")}else{setRound(round+1);setMessage(correct?"Correct. Play the next cue":"Incorrect. Play the next cue")}};
 return <section className={panel}><p role="status" aria-live="polite" className="text-center font-bold">{message}</p><Button onClick={play} className="w-full min-h-20 text-lg">Play direction cue</Button><div className="grid grid-cols-2 gap-3">{directions.map(direction=><Button key={direction} variant="outline" className="min-h-16 capitalize" onClick={()=>choose(direction)}>{direction}</Button>)}</div><p className="text-sm text-muted-foreground">The current shared audio layer announces a spatial direction. A dedicated binaural production pack remains scheduled.</p></section>}
