import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { useGameEconomy } from "@/components/game/GameEconomyGate";
import { gameManager } from "@/features/arcade/core/gameManager";
import { accessibilityAudio } from "@/features/arcade/audio/AccessibilityAudioLayer";
import { add2048Tile, canMove2048, createMineBoard, dropConnectFour, empty2048, emptyConnectFour, move2048, revealMineCell, winnerConnectFour, type ConnectBoard, type Direction, type Grid2048, type MineBoard } from "@/lib/games/arcadeExpansionEngines";

const panel = "mx-auto max-w-3xl space-y-5 p-4 sm:p-8";
const announce = (message:string) => accessibilityAudio.announce(message,"status");

export function Game2048() {
  const initial=()=>add2048Tile(add2048Tile(empty2048()));
  const [grid,setGrid]=useState<Grid2048>(initial); const [score,setScore]=useState(0); const {settleGameResult}=useGameEconomy();
  const reset=()=>{setGrid(initial());setScore(0)};
  const move=useCallback((direction:Direction)=>{ setGrid(current=>{ const result=move2048(current,direction); if(!result.moved)return current; const next=add2048Tile(result.grid); setScore(value=>{const total=value+result.score;gameManager.recordScore(total);return total}); const peak=Math.max(...next.flat()); announce(`${direction}. Highest tile ${peak}.`); if(peak>=2048) void settleGameResult("win","2048"); else if(!canMove2048(next)) void settleGameResult("loss","2048"); return next; }); },[settleGameResult]);
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{const direction=({ArrowLeft:"left",ArrowRight:"right",ArrowUp:"up",ArrowDown:"down"} as const)[event.key as "ArrowLeft"];if(direction){event.preventDefault();move(direction)}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[move]);
  return <section className={panel}><header className="flex items-center justify-between"><p className="font-bold">Score: <output aria-live="polite">{score}</output></p><Button onClick={reset} variant="outline">New game</Button></header><div role="grid" aria-label="2048 board. Use arrow keys to move tiles." className="grid grid-cols-4 gap-2 rounded-2xl bg-slate-900 p-3 sm:gap-3 sm:p-5">{grid.flatMap((row,r)=>row.map((value,c)=><div key={`${r}-${c}`} role="gridcell" aria-label={value?`Tile ${value}`:"Empty cell"} className={`grid aspect-square place-items-center rounded-xl text-xl font-black sm:text-3xl ${value?"bg-gradient-to-br from-violet-500 to-cyan-500 text-white":"bg-white/10"}`}>{value||""}</div>))}</div><div className="grid grid-cols-3 gap-2 sm:hidden" aria-label="Touch controls"><span/><Button onClick={()=>move("up")} aria-label="Move up">↑</Button><span/><Button onClick={()=>move("left")} aria-label="Move left">←</Button><Button onClick={()=>move("down")} aria-label="Move down">↓</Button><Button onClick={()=>move("right")} aria-label="Move right">→</Button></div><p className="text-sm text-muted-foreground">Combine equal tiles with the arrow keys or touch controls. Reach 2048 to win.</p></section>;
}

export function Minesweeper() {
  const [board,setBoard]=useState<MineBoard>(()=>createMineBoard()); const [status,setStatus]=useState<"playing"|"won"|"lost">("playing"); const {settleGameResult}=useGameEconomy();
  const reset=()=>{setBoard(createMineBoard());setStatus("playing")};
  const reveal=(r:number,c:number)=>{if(status!=="playing"||board[r][c].flagged)return; if(board[r][c].mine){const lost=board.map(row=>row.map(cell=>({...cell,revealed:cell.mine||cell.revealed})));setBoard(lost);setStatus("lost");announce("Mine. Round lost.");void settleGameResult("loss","Minesweeper");return} const next=revealMineCell(board,r,c);setBoard(next);const safe=next.flat().filter(cell=>!cell.mine);gameManager.recordScore(safe.filter(cell=>cell.revealed).length*10);if(safe.every(cell=>cell.revealed)){setStatus("won");announce("Minefield cleared.");void settleGameResult("win","Minesweeper")}};
  const flag=(r:number,c:number)=>{if(status!=="playing"||board[r][c].revealed)return;setBoard(current=>current.map((row,rr)=>row.map((cell,cc)=>rr===r&&cc===c?{...cell,flagged:!cell.flagged}:cell)))};
  return <section className={panel}><header className="flex items-center justify-between"><p role="status" className="font-bold">{status==="playing"?"10 mines — clear every safe cell":status==="won"?"Minefield cleared!":"A mine exploded"}</p><Button onClick={reset} variant="outline">New field</Button></header><div role="grid" aria-label="Nine by nine minesweeper board" className="mx-auto grid max-w-xl grid-cols-9 gap-1">{board.flatMap((row,r)=>row.map((cell,c)=><button key={`${r}-${c}`} role="gridcell" onClick={()=>reveal(r,c)} onContextMenu={e=>{e.preventDefault();flag(r,c)}} onKeyDown={e=>{if(e.key.toLowerCase()==="f"){e.preventDefault();flag(r,c)}}} aria-label={`Row ${r+1}, column ${c+1}: ${cell.revealed?(cell.mine?"mine":cell.adjacent?`${cell.adjacent} nearby mines`:"clear"):cell.flagged?"flagged":"hidden"}`} className={`aspect-square rounded text-xs font-black sm:text-base ${cell.revealed?cell.mine?"bg-rose-600 text-white":"bg-slate-200 text-slate-900":"bg-slate-800 text-cyan-200 hover:bg-slate-700"}`}>{cell.revealed?(cell.mine?"✦":cell.adjacent||""):cell.flagged?"⚑":""}</button>))}</div><p className="text-sm text-muted-foreground">Select a cell to reveal it. Press F on a focused cell, or long-press/context-click, to place a flag.</p></section>;
}

function chooseAiColumn(board:ConnectBoard){for(const player of [2,1] as const)for(let c=0;c<7;c++){const dropped=dropConnectFour(board,c,player);if(dropped.row>=0&&winnerConnectFour(dropped.board)===player)return c}return [3,2,4,1,5,0,6].find(c=>board[0][c]===0)??-1}
export function ConnectFour() {
  const [board,setBoard]=useState<ConnectBoard>(emptyConnectFour);const [message,setMessage]=useState("Your turn");const [finished,setFinished]=useState(false);const {settleGameResult}=useGameEconomy();
  const play=(column:number)=>{if(finished)return;const human=dropConnectFour(board,column,1);if(human.row<0)return;if(winnerConnectFour(human.board)){setBoard(human.board);setMessage("You connected four!");setFinished(true);gameManager.recordScore(400);void settleGameResult("win","Connect Four");return}const aiColumn=chooseAiColumn(human.board);if(aiColumn<0){setBoard(human.board);setMessage("Draw");setFinished(true);void settleGameResult("draw","Connect Four");return}const ai=dropConnectFour(human.board,aiColumn,2);setBoard(ai.board);if(winnerConnectFour(ai.board)){setMessage("Computer connected four");setFinished(true);void settleGameResult("loss","Connect Four")}else setMessage(`Computer played column ${aiColumn+1}. Your turn`);};
  return <section className={panel}><header className="flex items-center justify-between"><p role="status" aria-live="polite" className="font-bold">{message}</p><Button variant="outline" onClick={()=>{setBoard(emptyConnectFour());setFinished(false);setMessage("Your turn")}}>New match</Button></header><div role="grid" aria-label="Connect Four board" className="grid grid-cols-7 gap-2 rounded-2xl bg-blue-900 p-3">{board.flatMap((row,r)=>row.map((cell,c)=><button key={`${r}-${c}`} role="gridcell" onClick={()=>play(c)} aria-label={`Row ${r+1}, column ${c+1}: ${cell===1?"your disc":cell===2?"computer disc":"empty"}`} className={`aspect-square rounded-full border-2 border-blue-300/20 ${cell===1?"bg-amber-400":cell===2?"bg-fuchsia-500":"bg-slate-950 hover:bg-slate-800"}`} />))}</div><p className="text-sm text-muted-foreground">Choose any cell in a column to drop your amber disc. Connect four horizontally, vertically, or diagonally.</p></section>;
}

export function ReactionTest() {
  const [phase,setPhase]=useState<"idle"|"waiting"|"ready"|"result">("idle");const [result,setResult]=useState<number>();const timer=useRef<number>();const started=useRef(0);const {settleGameResult}=useGameEconomy();
  useEffect(()=>()=>window.clearTimeout(timer.current),[]);
  const begin=()=>{setPhase("waiting");setResult(undefined);timer.current=window.setTimeout(()=>{started.current=performance.now();setPhase("ready");announce("Go now")},1800+Math.random()*2500)};
  const hit=()=>{if(phase==="waiting"){window.clearTimeout(timer.current);setPhase("idle");announce("Too soon");return}if(phase!=="ready")return;const ms=Math.round(performance.now()-started.current);setResult(ms);setPhase("result");gameManager.recordScore(Math.max(0,1000-ms));if(ms<350)void settleGameResult("win","Reaction Test")};
  const label=phase==="idle"?"Start test":phase==="waiting"?"Wait for the signal…":phase==="ready"?"GO!":`${result} milliseconds — try again`;
  return <section className={panel}><button onClick={phase==="idle"||phase==="result"?begin:hit} className={`grid min-h-[22rem] w-full place-items-center rounded-3xl border-4 text-center text-2xl font-black focus-visible:ring-4 focus-visible:ring-cyan-300 ${phase==="ready"?"border-emerald-300 bg-emerald-500 text-slate-950":"border-violet-300/30 bg-slate-900 text-white"}`} aria-live="assertive"><span>{label}{phase==="waiting"&&<small className="mt-3 block text-base font-normal text-slate-300">Pressing early resets the test</small>}</span></button><p className="text-sm text-muted-foreground">Keyboard: focus the test area and press Space or Enter. Touch and pointer input are supported.</p></section>;
}
