import{useState}from"react";import{useLocation}from"react-router-dom";import{Button}from"@/components/ui/button";import{Progress}from"@/components/ui/progress";import{useGameEconomy}from"@/components/game/GameEconomyGate";import{gameManager}from"@/features/arcade/core/gameManager";import{applyManagementAction,createManagementState,managementResult,type ManagementAction}from"@/lib/games/arcadeManagementEngine";
type Config={title:string;objective:string;actions:ManagementAction[]};const configs:Record<string,Config>={
 "restaurant-manager":{title:"Restaurant Manager",objective:"Build service quality without exhausting cash or staff.",actions:[{id:"menu",label:"Improve the menu",cost:110,effects:{quality:18,people:3}},{id:"train",label:"Train the service team",cost:90,effects:{people:15,quality:8}},{id:"tables",label:"Add efficient seating",cost:140,effects:{capacity:20,cash:20}},{id:"campaign",label:"Run a local campaign",cost:75,effects:{cash:90,people:-5}}]},
 "farm-manager":{title:"Farm Manager",objective:"Balance yield, soil quality, workers, and operating cash.",actions:[{id:"soil",label:"Restore soil",cost:100,effects:{quality:20,capacity:5}},{id:"workers",label:"Support farm workers",cost:85,effects:{people:18,quality:4}},{id:"irrigation",label:"Upgrade irrigation",cost:150,effects:{capacity:25,quality:8}},{id:"market",label:"Sell seasonal produce",cost:40,effects:{cash:120,capacity:-8}}]},
 "city-builder":{title:"City Builder",objective:"Grow a balanced city with capacity, public trust, and service quality.",actions:[{id:"park",label:"Build a public park",cost:120,effects:{people:18,quality:12}},{id:"transit",label:"Expand transit",cost:160,effects:{capacity:22,quality:8}},{id:"housing",label:"Build mixed housing",cost:140,effects:{capacity:25,people:6}},{id:"tax",label:"Adjust local revenue",cost:20,effects:{cash:130,people:-10}}]},
 "delivery-simulator":{title:"Delivery Simulator",objective:"Expand delivery capacity while protecting drivers and service quality.",actions:[{id:"routes",label:"Optimize routes",cost:70,effects:{capacity:15,quality:8}},{id:"drivers",label:"Support drivers",cost:90,effects:{people:20,quality:5}},{id:"fleet",label:"Add efficient vehicles",cost:155,effects:{capacity:25,cash:20}},{id:"contracts",label:"Accept bulk contract",cost:45,effects:{cash:125,quality:-8}}]},
};
export default function ManagementGame(){const slug=useLocation().pathname.split("/").pop()!;const config=configs[slug]??configs["restaurant-manager"];const[state,setState]=useState(createManagementState),[message,setMessage]=useState(config.objective),[finished,setFinished]=useState(false);const{settleGameResult}=useGameEconomy();const act=(action:ManagementAction)=>{if(finished)return;const next=applyManagementAction(state,action);if(next===state){setMessage("Not enough cash for that action");return}setState(next);gameManager.recordScore(next.score);const result=managementResult(next);setMessage(`${action.label} completed. Turn ${Math.min(next.turn,8)}.`);if(result!=="playing"){setFinished(true);void settleGameResult(result,config.title)}};return <section className="mx-auto max-w-4xl space-y-6 p-4 sm:p-8"><header><p className="text-sm font-bold text-violet-600">Turn {Math.min(state.turn,8)} / 8</p><p className="mt-1">{config.objective}</p></header><div className="grid grid-cols-2 gap-3 sm:grid-cols-5"><Metric label="Cash" value={`$${state.cash}`}/><Metric label="People" value={state.people}/><Metric label="Quality" value={state.quality}/><Metric label="Capacity" value={state.capacity}/><Metric label="Score" value={state.score}/></div><div className="space-y-3"><Progress value={state.quality} aria-label="Quality"/><Progress value={state.people} aria-label="People"/></div><div className="grid gap-3 sm:grid-cols-2">{config.actions.map(action=><Button key={action.id} disabled={finished} variant="outline" className="h-auto min-h-20 justify-between whitespace-normal p-4 text-start" onClick={()=>act(action)}><span>{action.label}</span><span className="text-xs text-muted-foreground">−${action.cost}</span></Button>)}</div><p role="status" aria-live="polite" className="font-bold">{message}</p></section>}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-xl bg-slate-900 p-3 text-center text-white"><span className="block text-xs text-slate-400">{label}</span><strong>{value}</strong></div>}
