import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { useGameEconomy } from "@/components/game/GameEconomyGate";
import { playProductionSound } from "@/features/arcade/audio/playProductionSound";
import { gameManager } from "@/features/arcade/core/gameManager";
import { PhysicsLabMotion } from "@/features/arcade/motion/PhysicsLabMotion";
import { balancedLever, magneticForce, pendulumPeriod, physicsScore, projectileRange, torque } from "@/lib/games/arcadePhysicsLabEngine";

const panel="mx-auto max-w-3xl space-y-6 p-4 sm:p-8";
function Control({label,value,set,min=1,max=10}:{label:string;value:number;set:(n:number)=>void;min?:number;max?:number}){return <label className="space-y-2"><span className="flex justify-between font-bold"><span>{label}</span><output>{value}</output></span><Slider aria-label={label} value={[value]} onValueChange={v=>set(v[0])} min={min} max={max} step={1}/></label>}
function finishSound(won:boolean){void playProductionSound(won?"natural-victory":"natural-failure",{volume:.52})}

export function BalanceLab(){const[leftMass,setLeftMass]=useState(4),[leftDistance,setLeftDistance]=useState(3),[rightMass,setRightMass]=useState(3),[rightDistance,setRightDistance]=useState(3),[round,setRound]=useState(1),[score,setScore]=useState(0),[message,setMessage]=useState("Match the torque on both sides");const{settleGameResult}=useGameEconomy(),left=torque(leftMass,leftDistance),right=torque(rightMass,rightDistance);const check=()=>{const correct=balancedLever(leftMass,leftDistance,rightMass,rightDistance),next=score+(correct?100:physicsScore(Math.abs(left-right)));setScore(next);if(round===4){const won=next>=320;setMessage(`Lab complete: ${next} points`);gameManager.recordScore(next);finishSound(won);void settleGameResult(won?"win":"loss","Balance Lab")}else{setRound(round+1);setMessage(correct?"Balanced":"Torque difference: "+Math.abs(left-right))}};return <section className={panel}><header className="flex justify-between"><strong>Trial {round} / 4</strong><span>{score} points</span></header><div className="grid gap-6 sm:grid-cols-2"><Control label="Left mass" value={leftMass} set={setLeftMass}/><Control label="Left distance" value={leftDistance} set={setLeftDistance}/><Control label="Right mass" value={rightMass} set={setRightMass}/><Control label="Right distance" value={rightDistance} set={setRightDistance}/></div><PhysicsLabMotion kind="balance" value={left-right}/><div className="grid grid-cols-2 rounded-xl bg-slate-950 p-8 text-center text-2xl font-black text-white"><span>{left} Nm</span><span>{right} Nm</span></div><Button onClick={check} className="w-full">Test balance</Button><p role="status" aria-live="polite">{message}</p></section>}

export function PendulumPuzzle(){const[length,setLength]=useState(1),[estimate,setEstimate]=useState(2),[round,setRound]=useState(1),[score,setScore]=useState(0),[message,setMessage]=useState("Estimate the pendulum period");const{settleGameResult}=useGameEconomy();const check=()=>{const actual=pendulumPeriod(length),points=physicsScore(Math.abs(actual-estimate)*5),next=score+points;setScore(next);if(round===4){const won=next>=300;setMessage(`Lab complete: ${next} points`);gameManager.recordScore(next);finishSound(won);void settleGameResult(won?"win":"loss","Pendulum Puzzle")}else{setMessage(`Measured ${actual.toFixed(2)} seconds`);setRound(round+1);setLength(round+1)}};return <section className={panel}><header className="flex justify-between"><strong>Trial {round} / 4</strong><span>{score} points</span></header><PhysicsLabMotion kind="pendulum" value={length}/><Control label="Pendulum length (m)" value={length} set={setLength} min={1} max={4}/><Control label="Estimated period (seconds)" value={estimate} set={setEstimate} min={1} max={5}/><Button onClick={check} className="w-full">Measure period</Button><p role="status" aria-live="polite">{message}</p></section>}

export function TrajectoryMaster(){const[speed,setSpeed]=useState(20),[angle,setAngle]=useState(35),[target,setTarget]=useState(38),[round,setRound]=useState(1),[score,setScore]=useState(0),[attempt,setAttempt]=useState(0),[message,setMessage]=useState("Reach the target distance");const{settleGameResult}=useGameEconomy(),range=projectileRange(speed,angle);const launch=()=>{setAttempt(value=>value+1);const points=physicsScore(Math.abs(range-target)/2),next=score+points;setScore(next);if(round===5){const won=next>=350;setMessage(`Mission complete: ${next} points`);gameManager.recordScore(next);finishSound(won);void settleGameResult(won?"win":"loss","Trajectory Master")}else{setMessage(`Projectile travelled ${range.toFixed(1)} meters`);setRound(round+1);setTarget(target+4)}};return <section className={panel}><header className="flex justify-between"><strong>Launch {round} / 5</strong><span>Target {target} m · {score} points</span></header><PhysicsLabMotion kind="trajectory" value={range} attempt={attempt}/><Control label="Speed (m/s)" value={speed} set={setSpeed} min={10} max={30}/><Control label="Angle (degrees)" value={angle} set={setAngle} min={10} max={80}/><Button onClick={launch} className="w-full">Launch</Button><p role="status" aria-live="polite">{message}</p></section>}

export function MagnetLab(){const[a,setA]=useState(4),[b,setB]=useState(4),[distance,setDistance]=useState(2),[aligned,setAligned]=useState(true),[round,setRound]=useState(1),[score,setScore]=useState(0),[attempt,setAttempt]=useState(0),[message,setMessage]=useState("Predict attraction or repulsion");const{settleGameResult}=useGameEconomy(),force=magneticForce(a,b,distance,aligned);const predict=(attract:boolean)=>{setAttempt(value=>value+1);const correct=(force<0)===attract,next=score+(correct?100:0);setScore(next);if(round===5){const won=next>=400;setMessage(`Lab complete: ${next} points`);gameManager.recordScore(next);finishSound(won);void settleGameResult(won?"win":"loss","Magnet Lab")}else{setMessage(correct?`Correct. Force magnitude ${Math.abs(force).toFixed(1)}`:"Incorrect polarity prediction");setRound(round+1);setAligned(!aligned);setDistance(Math.min(5,distance+1))}};return <section className={panel}><header className="flex justify-between"><strong>Trial {round} / 5</strong><span>{score} points</span></header><PhysicsLabMotion kind="magnet" value={distance} attracting={!aligned} attempt={attempt}/><Control label="Magnet A strength" value={a} set={setA}/><Control label="Magnet B strength" value={b} set={setB}/><Control label="Distance" value={distance} set={setDistance} min={1} max={5}/><div className="grid grid-cols-2 gap-3"><Button onClick={()=>predict(true)}>Attract</Button><Button onClick={()=>predict(false)}>Repel</Button></div><p role="status" aria-live="polite">{message}</p></section>}
