import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { useGameEconomy } from "@/components/game/GameEconomyGate";
import { playProductionSound } from "@/features/arcade/audio/playProductionSound";
import { gameManager } from "@/features/arcade/core/gameManager";
import { SportsActionMotion } from "@/features/arcade/motion/SportsActionMotion";
import { archeryScore, bowlingPins, dartScore, golfStrokes, targetDistance } from "@/lib/games/arcadeSportsPackEngines";

const panel="mx-auto max-w-3xl space-y-6 p-4 sm:p-8";
function Controls({power,setPower,accuracy,setAccuracy}:{power:number;setPower:(n:number)=>void;accuracy:number;setAccuracy:(n:number)=>void}){return <div className="grid gap-6 sm:grid-cols-2"><Control label="Power" value={power} onChange={setPower} suffix="%"/><Control label="Aim" value={accuracy} onChange={setAccuracy}/></div>}
function Control({label,value,onChange,suffix=""}:{label:string;value:number;onChange:(n:number)=>void;suffix?:string}){return <label className="space-y-3"><span className="flex justify-between font-bold">{label} <output>{value}{suffix}</output></span><Slider aria-label={label} value={[value]} onValueChange={([next])=>onChange(next)} min={1} max={100}/></label>}
export function MiniGolf(){const[power,setPower]=useState(50),[accuracy,setAccuracy]=useState(50),[hole,setHole]=useState(1),[total,setTotal]=useState(0),[message,setMessage]=useState("Calibrate the shot"),[attempt,setAttempt]=useState(0),[success,setSuccess]=useState<boolean|null>(null);const{settleGameResult}=useGameEconomy();const shoot=()=>{const distance=targetDistance(power,accuracy,45+hole*6),strokes=golfStrokes(distance),next=total+strokes,holed=distance<8;setTotal(next);setAttempt(v=>v+1);setSuccess(holed);setMessage(holed?`Hole ${hole}: holed in one`:`Hole ${hole}: ${strokes} strokes`);if(hole===5){const won=next<=12;gameManager.recordScore(Math.max(100,2000-next*80));void playProductionSound(won?"natural-victory":"natural-failure",{volume:.55});void settleGameResult(won?"win":"loss","Mini Golf")}else setHole(hole+1)};return <section className={panel}><header className="flex justify-between"><strong>Hole {hole} / 5</strong><span>{total} strokes</span></header><SportsActionMotion sport="mini-golf" attempt={attempt} scored={success}/><Controls power={power} setPower={setPower} accuracy={accuracy} setAccuracy={setAccuracy}/><Button onClick={shoot} className="w-full">Putt</Button><p role="status" aria-live="polite" className="font-bold">{message}</p></section>}
export function Bowling(){const[power,setPower]=useState(60),[accuracy,setAccuracy]=useState(50),[frame,setFrame]=useState(1),[score,setScore]=useState(0),[message,setMessage]=useState("Set your release"),[attempt,setAttempt]=useState(0),[strike,setStrike]=useState<boolean|null>(null);const{settleGameResult}=useGameEconomy();const roll=()=>{const pins=bowlingPins(power,accuracy),next=score+pins;setScore(next);setAttempt(v=>v+1);setStrike(pins===10);setMessage(pins===10?"Strike!":`${pins} pins`);if(frame===10){const won=next>=70;gameManager.recordScore(next*10);void playProductionSound(won?"natural-victory":"natural-failure",{volume:.55});void settleGameResult(won?"win":"loss","Bowling")}else setFrame(frame+1)};return <section className={panel}><header className="flex justify-between"><strong>Frame {frame} / 10</strong><span>{score} pins</span></header><SportsActionMotion sport="bowling" attempt={attempt} scored={strike}/><Controls power={power} setPower={setPower} accuracy={accuracy} setAccuracy={setAccuracy}/><Button onClick={roll} className="w-full">Roll</Button><p role="status" aria-live="polite" className="font-bold">{message}</p></section>}
export function Archery(){const[power,setPower]=useState(55),[accuracy,setAccuracy]=useState(50),[arrow,setArrow]=useState(1),[score,setScore]=useState(0),[message,setMessage]=useState("Aim for the center"),[attempt,setAttempt]=useState(0),[bullseye,setBullseye]=useState<boolean|null>(null);const{settleGameResult}=useGameEconomy();const shoot=()=>{const points=archeryScore(power,accuracy),next=score+points;setScore(next);setAttempt(v=>v+1);setBullseye(points===10);setMessage(`${points} points`);if(arrow===10){const won=next>=70;gameManager.recordScore(next*10);void playProductionSound(won?"natural-victory":"natural-failure",{volume:.55});void settleGameResult(won?"win":"loss","Archery")}else setArrow(arrow+1)};return <section className={panel}><header className="flex justify-between"><strong>Arrow {arrow} / 10</strong><span>{score} points</span></header><SportsActionMotion sport="archery" attempt={attempt} scored={bullseye}/><Controls power={power} setPower={setPower} accuracy={accuracy} setAccuracy={setAccuracy}/><Button onClick={shoot} className="w-full">Release arrow</Button><p role="status" aria-live="polite" className="font-bold">{message}</p></section>}
export function Darts(){const[x,setX]=useState(50),[y,setY]=useState(50),[dart,setDart]=useState(1),[score,setScore]=useState(0),[message,setMessage]=useState("Set horizontal and vertical aim"),[attempt,setAttempt]=useState(0),[bullseye,setBullseye]=useState<boolean|null>(null);const{settleGameResult}=useGameEconomy();const throwDart=()=>{const points=dartScore(x,y),next=score+points;setScore(next);setAttempt(v=>v+1);setBullseye(points===50);setMessage(`${points} points`);if(dart===9){const won=next>=180;gameManager.recordScore(next);void playProductionSound(won?"natural-victory":"natural-failure",{volume:.55});void settleGameResult(won?"win":"loss","Darts")}else setDart(dart+1)};return <section className={panel}><header className="flex justify-between"><strong>Dart {dart} / 9</strong><span>{score} points</span></header><SportsActionMotion sport="darts" attempt={attempt} scored={bullseye}/><Controls power={x} setPower={setX} accuracy={y} setAccuracy={setY}/><Button onClick={throwDart} className="w-full">Throw dart</Button><p role="status" aria-live="polite" className="font-bold">{message}</p></section>}
