// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
// Supabase now calls this the publishable key, while older deployments and
// Docker images still expose the same client-safe value as ANON_KEY.
const SUPABASE_PUBLISHABLE_KEY = (
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
  ?? import.meta.env.VITE_SUPABASE_ANON_KEY
) as string | undefined;

// Validate at startup so a missing env var surfaces as a clear console error
// rather than a cryptic module-level crash that kills the whole app.
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    "[supabase] Missing environment variables.\n" +
    "  VITE_SUPABASE_URL:", SUPABASE_URL ? "✓" : "✗ MISSING",
    "\n  VITE_SUPABASE_PUBLISHABLE_KEY or VITE_SUPABASE_ANON_KEY:",
    SUPABASE_PUBLISHABLE_KEY ? "✓" : "✗ MISSING",
    "\nMake sure these are set in your deployment environment."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use a safe fallback URL so createClient doesn't throw on missing vars
// (the app will still show an auth error, but won't white-screen)
export const supabase = createClient<Database>(
  SUPABASE_URL    ?? "https://placeholder.supabase.co",
  SUPABASE_PUBLISHABLE_KEY ?? "placeholder",
  {
    auth: {
      // Fall back to sessionStorage if localStorage is unavailable
      // (some browsers restrict it in private/incognito mode)
      storage: (() => {
        try { localStorage.setItem("__sb_test", "1"); localStorage.removeItem("__sb_test"); return localStorage; }
        catch { return sessionStorage; }
      })(),
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
